#!/usr/bin/env python3
"""Assemble the extended difftest cases into tests/difftest/cases_gen.inc.

Each line of CASES is (name, flag mask, setup function, assembly). The bytes
are produced with GNU as (Intel syntax) so nobody hand-encodes ModRM again;
the .inc is checked in so the test builds on machines without an assembler.

    python3 tests/difftest/cases_gen.py

Flag masks are the flags the SDM says are defined afterwards; anything else
is not compared (real CPUs disagree about undefined flags).
"""
import subprocess, tempfile, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))

# (name, mask, setup, asm)            -- integer / SSE
# (name, mask, setup, asm, fsw, fuzzy) -- x87; fsw is FSW_ALL / FSW_NOCC / FSW_TOP
CASES = [
    # --- integer odds and ends ---
    ("cmpxchg rcx,rbx (miss)",      "ALL", "0",       "cmpxchg rcx, rbx"),
    ("cmpxchg rcx,rbx (hit)",       "ALL", "s_eqc",   "cmpxchg rcx, rbx"),
    ("cmpxchg [rdi],rbx",           "ALL", "0",       "cmpxchg [rdi], rbx"),
    ("cmpxchg ecx,ebx (hit)",       "ALL", "s_eqc32", "cmpxchg ecx, ebx"),
    ("xadd rax,rbx",                "ALL", "0",       "xadd rax, rbx"),
    ("xadd [rdi],ecx",              "ALL", "0",       "xadd [rdi], ecx"),
    ("bswap eax",                   "ALL", "0",       "bswap eax"),
    ("bswap r9",                    "ALL", "0",       "bswap r9"),
    ("bsf rax,rbx",                 "ZF",  "0",       "bsf rax, rbx"),
    ("bsr ecx,edx",                 "ZF",  "0",       "bsr ecx, edx"),
    ("bsf rax,rbx (zero)",          "ZF",  "s_rbx0",  "bsf rax, rbx"),
    ("bsr rax,rbx (zero)",          "ZF",  "s_rbx0",  "bsr rax, rbx"),
    ("tzcnt rax,rbx",               "CZ",  "0",       "tzcnt rax, rbx"),
    ("lzcnt ecx,edx",               "CZ",  "0",       "lzcnt ecx, edx"),
    ("tzcnt rax,rbx (zero)",        "CZ",  "s_rbx0",  "tzcnt rax, rbx"),
    ("popcnt rax,rbx",              "ALL", "0",       "popcnt rax, rbx"),
    ("popcnt ecx,edx",              "ALL", "0",       "popcnt ecx, edx"),
    ("shld rax,rbx,5",              "SHN", "0",       "shld rax, rbx, 5"),
    ("shld eax,ebx,1",              "SH1", "0",       "shld eax, ebx, 1"),
    ("shrd rax,rbx,cl (cl=7)",      "SHN", "s_cl7",   "shrd rax, rbx, cl"),
    ("shrd ecx,edx,9",              "SHN", "0",       "shrd ecx, edx, 9"),
    ("rcl rax,1",                   "ALL", "0",       "rcl rax, 1"),
    ("rcl eax,cl (cl=7)",           "NO_OF", "s_cl7", "rcl eax, cl"),
    ("rcr rdx,3",                   "NO_OF", "0",     "rcr rdx, 3"),
    ("rcr al,1",                    "ALL", "0",       "rcr al, 1"),
    ("lahf",                        "ALL", "0",       "lahf"),
    ("sahf",                        "ALL", "0",       "sahf"),
    ("clc",                         "ALL", "0",       "clc"),
    ("stc",                         "ALL", "0",       "stc"),
    ("cmc",                         "ALL", "0",       "cmc"),
    ("bt rax,rbx",                  "CF",  "0",       "bt rax, rbx"),
    ("bts ecx,5",                   "CF",  "0",       "bts ecx, 5"),
    ("btr rax,rbx",                 "CF",  "0",       "btr rax, rbx"),
    ("btc rdx,63",                  "CF",  "0",       "btc rdx, 63"),
    ("bts [rdi],rcx (rcx=100)",     "CF",  "s_rcx100","bts [rdi], rcx"),
    ("btc dword[rdi],ecx (ecx=100)","CF",  "s_rcx100","btc dword ptr [rdi], ecx"),
    ("bt word[rdi+2],5",            "CF",  "0",       "bt word ptr [rdi+2], 5"),
    ("repe cmpsb (rcx=16)",         "ALL", "s_rcx16", "repe cmpsb"),
    ("repne scasb (rcx=16)",        "ALL", "s_rcx16", "repne scasb"),
    ("cmpsq",                       "ALL", "0",       "cmpsq"),
    ("scasd",                       "ALL", "0",       "scasd"),
    ("lodsq",                       "ALL", "0",       "lodsq"),
    ("lodsb",                       "ALL", "0",       "lodsb"),
    ("add rax,rbx; loop (rcx=4)",   "ALL", "s_rcx4",  "1: add rax, rbx\n loop 1b"),
    ("movnti [rdi],rax",            "ALL", "0",       "movnti [rdi], rax"),
    ("prefetcht0; lfence; mfence",  "ALL", "0",       "prefetcht0 [rdi]\n lfence\n mfence"),

    # --- SSE moves ---
    ("movaps xmm0,xmm1",            "ALL", "0", "movaps xmm0, xmm1"),
    ("movdqa [rdi],xmm2",           "ALL", "0", "movdqa [rdi], xmm2"),
    ("movdqu xmm3,[rdi+16]",        "ALL", "0", "movdqu xmm3, [rdi+16]"),
    ("movups xmm12,[rsi]",          "ALL", "0", "movups xmm12, [rsi]"),
    ("movq rax,xmm0",               "ALL", "0", "movq rax, xmm0"),
    ("movq xmm5,rbx",               "ALL", "0", "movq xmm5, rbx"),
    ("movq xmm1,xmm0",              "ALL", "0", "movq xmm1, xmm0"),
    ("movq xmm4,[rdi]",             "ALL", "0", "movq xmm4, [rdi]"),
    ("movq [rdi],xmm4",             "ALL", "0", "movq [rdi], xmm4"),
    ("movd eax,xmm2",               "ALL", "0", "movd eax, xmm2"),
    ("movd xmm6,ecx",               "ALL", "0", "movd xmm6, ecx"),
    ("movd [rdi],xmm2",             "ALL", "0", "movd [rdi], xmm2"),
    ("movsd xmm9,xmm11 (merge)",    "ALL", "0", "movsd xmm9, xmm11"),
    ("movsd xmm9,[rdi] (zext)",     "ALL", "0", "movsd xmm9, [rdi]"),
    ("movsd [rdi],xmm9",            "ALL", "0", "movsd [rdi], xmm9"),
    ("movss xmm8,xmm10 (merge)",    "ALL", "0", "movss xmm8, xmm10"),
    ("movss xmm8,[rdi] (zext)",     "ALL", "0", "movss xmm8, [rdi]"),
    ("movss [rdi],xmm8",            "ALL", "0", "movss [rdi], xmm8"),
    ("movlps xmm0,[rdi]",           "ALL", "0", "movlps xmm0, [rdi]"),
    ("movhps xmm0,[rdi]",           "ALL", "0", "movhps xmm0, [rdi]"),
    ("movhps [rdi],xmm1",           "ALL", "0", "movhps [rdi], xmm1"),
    ("movlpd [rdi],xmm1",           "ALL", "0", "movlpd [rdi], xmm1"),
    ("movhlps xmm0,xmm1",           "ALL", "0", "movhlps xmm0, xmm1"),
    ("movlhps xmm0,xmm1",           "ALL", "0", "movlhps xmm0, xmm1"),
    ("movmskps eax,xmm0",           "ALL", "0", "movmskps eax, xmm0"),
    ("movmskpd ecx,xmm1",           "ALL", "0", "movmskpd ecx, xmm1"),
    ("pmovmskb eax,xmm2",           "ALL", "0", "pmovmskb eax, xmm2"),
    ("pextrw eax,xmm3,5",           "ALL", "0", "pextrw eax, xmm3, 5"),
    ("pinsrw xmm3,ecx,2",           "ALL", "0", "pinsrw xmm3, ecx, 2"),

    # --- SSE integer ---
    ("pxor xmm0,xmm1",              "ALL", "0", "pxor xmm0, xmm1"),
    ("pxor xmm0,xmm0",              "ALL", "0", "pxor xmm0, xmm0"),
    ("por xmm2,[rdi]",              "ALL", "0", "por xmm2, [rdi]"),
    ("pand xmm3,xmm4",              "ALL", "0", "pand xmm3, xmm4"),
    ("pandn xmm5,xmm6",             "ALL", "0", "pandn xmm5, xmm6"),
    ("xorps xmm7,xmm0",             "ALL", "0", "xorps xmm7, xmm0"),
    ("andnpd xmm1,xmm2",            "ALL", "0", "andnpd xmm1, xmm2"),
    ("paddb xmm0,xmm1",             "ALL", "0", "paddb xmm0, xmm1"),
    ("paddw xmm2,xmm3",             "ALL", "0", "paddw xmm2, xmm3"),
    ("paddd xmm4,xmm5",             "ALL", "0", "paddd xmm4, xmm5"),
    ("paddq xmm6,xmm7",             "ALL", "0", "paddq xmm6, xmm7"),
    ("psubb xmm0,xmm1",             "ALL", "0", "psubb xmm0, xmm1"),
    ("psubw xmm2,xmm3",             "ALL", "0", "psubw xmm2, xmm3"),
    ("psubd xmm4,[rdi]",            "ALL", "0", "psubd xmm4, [rdi]"),
    ("psubq xmm6,xmm7",             "ALL", "0", "psubq xmm6, xmm7"),
    ("paddusb xmm0,xmm1",           "ALL", "0", "paddusb xmm0, xmm1"),
    ("paddusw xmm2,xmm3",           "ALL", "0", "paddusw xmm2, xmm3"),
    ("paddsb xmm4,xmm5",            "ALL", "0", "paddsb xmm4, xmm5"),
    ("paddsw xmm6,xmm7",            "ALL", "0", "paddsw xmm6, xmm7"),
    ("psubusb xmm0,xmm1",           "ALL", "0", "psubusb xmm0, xmm1"),
    ("psubusw xmm2,xmm3",           "ALL", "0", "psubusw xmm2, xmm3"),
    ("psubsb xmm4,xmm5",            "ALL", "0", "psubsb xmm4, xmm5"),
    ("psubsw xmm6,xmm7",            "ALL", "0", "psubsw xmm6, xmm7"),
    ("pavgb xmm0,xmm1",             "ALL", "0", "pavgb xmm0, xmm1"),
    ("pavgw xmm2,xmm3",             "ALL", "0", "pavgw xmm2, xmm3"),
    ("pminub xmm4,xmm5",            "ALL", "0", "pminub xmm4, xmm5"),
    ("pmaxub xmm6,xmm7",            "ALL", "0", "pmaxub xmm6, xmm7"),
    ("pminsw xmm0,xmm1",            "ALL", "0", "pminsw xmm0, xmm1"),
    ("pmaxsw xmm2,xmm3",            "ALL", "0", "pmaxsw xmm2, xmm3"),
    ("psadbw xmm4,xmm5",            "ALL", "0", "psadbw xmm4, xmm5"),
    ("pcmpeqb xmm0,xmm1",           "ALL", "0", "pcmpeqb xmm0, xmm1"),
    ("pcmpeqb xmm0,xmm0",           "ALL", "0", "pcmpeqb xmm0, xmm0"),
    ("pcmpeqw xmm2,xmm3",           "ALL", "0", "pcmpeqw xmm2, xmm3"),
    ("pcmpeqd xmm4,xmm5",           "ALL", "0", "pcmpeqd xmm4, xmm5"),
    ("pcmpgtb xmm6,xmm7",           "ALL", "0", "pcmpgtb xmm6, xmm7"),
    ("pcmpgtw xmm0,xmm1",           "ALL", "0", "pcmpgtw xmm0, xmm1"),
    ("pcmpgtd xmm2,xmm3",           "ALL", "0", "pcmpgtd xmm2, xmm3"),
    ("pmullw xmm4,xmm5",            "ALL", "0", "pmullw xmm4, xmm5"),
    ("pmulhw xmm6,xmm7",            "ALL", "0", "pmulhw xmm6, xmm7"),
    ("pmulhuw xmm0,xmm1",           "ALL", "0", "pmulhuw xmm0, xmm1"),
    ("pmuludq xmm2,xmm3",           "ALL", "0", "pmuludq xmm2, xmm3"),
    ("pmaddwd xmm4,xmm5",           "ALL", "0", "pmaddwd xmm4, xmm5"),
    ("psllw xmm0,3",                "ALL", "0", "psllw xmm0, 3"),
    ("pslld xmm1,17",               "ALL", "0", "pslld xmm1, 17"),
    ("psllq xmm2,40",               "ALL", "0", "psllq xmm2, 40"),
    ("psrlw xmm3,7",                "ALL", "0", "psrlw xmm3, 7"),
    ("psrld xmm4,1",                "ALL", "0", "psrld xmm4, 1"),
    ("psrlq xmm5,63",               "ALL", "0", "psrlq xmm5, 63"),
    ("psraw xmm6,4",                "ALL", "0", "psraw xmm6, 4"),
    ("psrad xmm7,31",               "ALL", "0", "psrad xmm7, 31"),
    ("psrad xmm7,40 (over)",        "ALL", "0", "psrad xmm7, 40"),
    ("psllq xmm0,xmm1 (count reg)", "ALL", "0", "psllq xmm0, xmm1"),
    ("pslldq xmm2,5",               "ALL", "0", "pslldq xmm2, 5"),
    ("psrldq xmm3,9",               "ALL", "0", "psrldq xmm3, 9"),
    ("pshufd xmm0,xmm1,0x1B",       "ALL", "0", "pshufd xmm0, xmm1, 0x1B"),
    ("pshuflw xmm2,xmm3,0x4E",      "ALL", "0", "pshuflw xmm2, xmm3, 0x4E"),
    ("pshufhw xmm4,xmm5,0xB1",      "ALL", "0", "pshufhw xmm4, xmm5, 0xB1"),
    ("shufps xmm6,xmm7,0x93",       "ALL", "0", "shufps xmm6, xmm7, 0x93"),
    ("shufpd xmm0,xmm1,1",          "ALL", "0", "shufpd xmm0, xmm1, 1"),
    ("punpcklbw xmm0,xmm1",         "ALL", "0", "punpcklbw xmm0, xmm1"),
    ("punpckhbw xmm2,xmm3",         "ALL", "0", "punpckhbw xmm2, xmm3"),
    ("punpcklwd xmm4,xmm5",         "ALL", "0", "punpcklwd xmm4, xmm5"),
    ("punpckhwd xmm6,xmm7",         "ALL", "0", "punpckhwd xmm6, xmm7"),
    ("punpckldq xmm0,xmm1",         "ALL", "0", "punpckldq xmm0, xmm1"),
    ("punpckhdq xmm2,xmm3",         "ALL", "0", "punpckhdq xmm2, xmm3"),
    ("punpcklqdq xmm4,xmm5",        "ALL", "0", "punpcklqdq xmm4, xmm5"),
    ("punpckhqdq xmm6,xmm7",        "ALL", "0", "punpckhqdq xmm6, xmm7"),
    ("unpcklps xmm0,xmm1",          "ALL", "0", "unpcklps xmm0, xmm1"),
    ("unpckhpd xmm2,xmm3",          "ALL", "0", "unpckhpd xmm2, xmm3"),
    ("packuswb xmm0,xmm1",          "ALL", "0", "packuswb xmm0, xmm1"),
    ("packsswb xmm2,xmm3",          "ALL", "0", "packsswb xmm2, xmm3"),
    ("packssdw xmm4,xmm5",          "ALL", "0", "packssdw xmm4, xmm5"),

    # --- SSE floating point (xmm8-15 hold modest values; see seed_xmm) ---
    ("addsd xmm9,xmm11",            "ALL", "0", "addsd xmm9, xmm11"),
    ("subsd xmm9,xmm11",            "ALL", "0", "subsd xmm9, xmm11"),
    ("mulsd xmm9,xmm11",            "ALL", "0", "mulsd xmm9, xmm11"),
    ("divsd xmm9,xmm11",            "ALL", "0", "divsd xmm9, xmm11"),
    ("minsd xmm9,xmm11",            "ALL", "0", "minsd xmm9, xmm11"),
    ("maxsd xmm9,xmm11",            "ALL", "0", "maxsd xmm9, xmm11"),
    ("sqrtsd xmm9,xmm11",           "ALL", "0", "sqrtsd xmm9, xmm11"),
    ("addsd xmm9,[rdi] (soup)",     "ALL", "0", "addsd xmm9, [rdi]"),
    ("addss xmm8,xmm10",            "ALL", "0", "addss xmm8, xmm10"),
    ("subss xmm8,xmm10",            "ALL", "0", "subss xmm8, xmm10"),
    ("mulss xmm8,xmm10",            "ALL", "0", "mulss xmm8, xmm10"),
    ("divss xmm8,xmm10",            "ALL", "0", "divss xmm8, xmm10"),
    ("minss xmm8,xmm10",            "ALL", "0", "minss xmm8, xmm10"),
    ("maxss xmm8,xmm10",            "ALL", "0", "maxss xmm8, xmm10"),
    ("sqrtss xmm8,xmm10",           "ALL", "0", "sqrtss xmm8, xmm10"),
    ("addpd xmm9,xmm13",            "ALL", "0", "addpd xmm9, xmm13"),
    ("subpd xmm9,xmm13",            "ALL", "0", "subpd xmm9, xmm13"),
    ("mulpd xmm9,xmm13",            "ALL", "0", "mulpd xmm9, xmm13"),
    ("divpd xmm9,xmm13",            "ALL", "0", "divpd xmm9, xmm13"),
    ("minpd xmm9,xmm13",            "ALL", "0", "minpd xmm9, xmm13"),
    ("maxpd xmm9,xmm13",            "ALL", "0", "maxpd xmm9, xmm13"),
    ("sqrtpd xmm9,xmm13",           "ALL", "0", "sqrtpd xmm9, xmm13"),
    ("addps xmm8,xmm12",            "ALL", "0", "addps xmm8, xmm12"),
    ("subps xmm8,xmm12",            "ALL", "0", "subps xmm8, xmm12"),
    ("mulps xmm8,xmm12",            "ALL", "0", "mulps xmm8, xmm12"),
    ("divps xmm8,xmm12",            "ALL", "0", "divps xmm8, xmm12"),
    ("minps xmm8,xmm12",            "ALL", "0", "minps xmm8, xmm12"),
    ("maxps xmm8,xmm12",            "ALL", "0", "maxps xmm8, xmm12"),
    ("sqrtps xmm8,xmm12",           "ALL", "0", "sqrtps xmm8, xmm12"),
    ("addpd xmm0,xmm1 (soup/NaN)",  "ALL", "0", "addpd xmm0, xmm1"),
    ("mulps xmm2,xmm3 (soup/NaN)",  "ALL", "0", "mulps xmm2, xmm3"),
    ("comisd xmm9,xmm11",           "ALL", "0", "comisd xmm9, xmm11"),
    ("ucomisd xmm9,xmm9 (equal)",   "ALL", "0", "ucomisd xmm9, xmm9"),
    ("ucomiss xmm8,xmm10",          "ALL", "0", "ucomiss xmm8, xmm10"),
    ("comiss xmm10,xmm8",           "ALL", "0", "comiss xmm10, xmm8"),
    ("pcmpeqd;ucomisd (NaN)",       "ALL", "0", "pcmpeqd xmm0, xmm0\n ucomisd xmm0, xmm9"),
    ("cmpsd xmm9,xmm11,1 (lt)",     "ALL", "0", "cmpltsd xmm9, xmm11"),
    ("cmpsd xmm9,xmm11,5 (nlt)",    "ALL", "0", "cmpnltsd xmm9, xmm11"),
    ("cmpss xmm8,xmm10,2 (le)",     "ALL", "0", "cmpless xmm8, xmm10"),
    ("cmppd xmm9,xmm13,4 (neq)",    "ALL", "0", "cmpneqpd xmm9, xmm13"),
    ("cmpps xmm8,xmm12,6 (nle)",    "ALL", "0", "cmpnleps xmm8, xmm12"),
    ("cmpps xmm0,xmm1,3 (unord)",   "ALL", "0", "cmpunordps xmm0, xmm1"),
    ("cvtsi2sd xmm9,rcx",           "ALL", "0", "cvtsi2sd xmm9, rcx"),
    ("cvtsi2sd xmm9,ecx",           "ALL", "0", "cvtsi2sd xmm9, ecx"),
    ("cvtsi2ss xmm8,rdx",           "ALL", "0", "cvtsi2ss xmm8, rdx"),
    ("cvttsd2si rax,xmm9",          "ALL", "0", "cvttsd2si rax, xmm9"),
    ("cvttsd2si eax,xmm9",          "ALL", "0", "cvttsd2si eax, xmm9"),
    ("cvtsd2si rax,xmm9",           "ALL", "0", "cvtsd2si rax, xmm9"),
    ("cvttss2si rax,xmm8",          "ALL", "0", "cvttss2si rax, xmm8"),
    ("cvtss2si ecx,xmm8",           "ALL", "0", "cvtss2si ecx, xmm8"),
    ("cvttsd2si rax,xmm0 (soup)",   "ALL", "0", "cvttsd2si rax, xmm0"),
    ("cvtsd2ss xmm8,xmm9",          "ALL", "0", "cvtsd2ss xmm8, xmm9"),
    ("cvtss2sd xmm9,xmm8",          "ALL", "0", "cvtss2sd xmm9, xmm8"),
    ("cvtdq2ps xmm8,xmm0",          "ALL", "0", "cvtdq2ps xmm8, xmm0"),
    ("cvtdq2pd xmm9,xmm0",          "ALL", "0", "cvtdq2pd xmm9, xmm0"),
    ("cvtps2dq xmm0,xmm8",          "ALL", "0", "cvtps2dq xmm0, xmm8"),
    ("cvttps2dq xmm0,xmm8",         "ALL", "0", "cvttps2dq xmm0, xmm8"),
    ("cvtpd2dq xmm0,xmm9",          "ALL", "0", "cvtpd2dq xmm0, xmm9"),
    ("cvttpd2dq xmm0,xmm9",         "ALL", "0", "cvttpd2dq xmm0, xmm9"),
    ("cvtps2pd xmm9,xmm8",          "ALL", "0", "cvtps2pd xmm9, xmm8"),
    ("cvtpd2ps xmm8,xmm9",          "ALL", "0", "cvtpd2ps xmm8, xmm9"),
    ("stmxcsr [rdi]",               "ALL", "0", "stmxcsr [rdi]"),

    # --- x87 (the stack starts with 3..6 valid registers; see seed_x87) ---
    ("fld st1",                     "ALL", "0", "fld st(1)",                 "FSW_ALL", 0),
    ("fld qword [rdi]",             "ALL", "0", "fld qword ptr [rdi]",       "FSW_ALL", 0),
    ("fld dword [rdi]",             "ALL", "0", "fld dword ptr [rdi]",       "FSW_ALL", 0),
    ("fld tbyte [rdi]",             "ALL", "0", "fld tbyte ptr [rdi]",       "FSW_ALL", 0),
    ("fild dword [rdi]",            "ALL", "0", "fild dword ptr [rdi]",      "FSW_ALL", 0),
    ("fild qword [rdi]",            "ALL", "0", "fild qword ptr [rdi]",      "FSW_ALL", 0),
    ("fild word [rdi]",             "ALL", "0", "fild word ptr [rdi]",       "FSW_ALL", 0),
    ("fld1; fldz; fldpi",           "ALL", "0", "fld1\n fldz\n fldpi",        "FSW_ALL", 0),
    ("fldl2e; fldln2",              "ALL", "0", "fldl2e\n fldln2",            "FSW_ALL", 0),
    ("fst qword [rdi]",             "ALL", "0", "fst qword ptr [rdi]",       "FSW_NOCC", 0),
    ("fstp dword [rdi]",            "ALL", "0", "fstp dword ptr [rdi]",      "FSW_NOCC", 0),
    ("fstp tbyte [rdi]",            "ALL", "0", "fstp tbyte ptr [rdi]",      "FSW_ALL", 0),
    ("fstp st2",                    "ALL", "0", "fstp st(2)",                "FSW_ALL", 0),
    ("fst st3",                     "ALL", "0", "fst st(3)",                 "FSW_ALL", 0),
    ("fistp qword [rdi]",           "ALL", "0", "fistp qword ptr [rdi]",     "FSW_NOCC", 0),
    ("fistp dword [rdi]",           "ALL", "0", "fistp dword ptr [rdi]",     "FSW_NOCC", 0),
    ("fist word [rdi]",             "ALL", "0", "fist word ptr [rdi]",       "FSW_NOCC", 0),
    ("fisttp qword [rdi]",          "ALL", "0", "fisttp qword ptr [rdi]",    "FSW_NOCC", 0),
    ("fisttp dword [rdi]",          "ALL", "0", "fisttp dword ptr [rdi]",    "FSW_NOCC", 0),
    ("fxch st2",                    "ALL", "0", "fxch st(2)",                "FSW_ALL", 0),
    ("fxch",                        "ALL", "0", "fxch",                      "FSW_ALL", 0),
    ("fadd st0,st1",                "ALL", "0", "fadd st(0), st(1)",         "FSW_NOCC", 0),
    ("fadd st2,st0",                "ALL", "0", "fadd st(2), st(0)",         "FSW_NOCC", 0),
    ("faddp st1,st0",               "ALL", "0", "faddp st(1), st(0)",        "FSW_NOCC", 0),
    ("faddp",                       "ALL", "0", "faddp",                     "FSW_NOCC", 0),
    ("fadd qword [rdi]",            "ALL", "0", "fadd qword ptr [rdi]",      "FSW_NOCC", 0),
    ("fadd dword [rdi]",            "ALL", "0", "fadd dword ptr [rdi]",      "FSW_NOCC", 0),
    ("fiadd dword [rdi]",           "ALL", "0", "fiadd dword ptr [rdi]",     "FSW_NOCC", 0),
    ("fsub st0,st1",                "ALL", "0", "fsub st(0), st(1)",         "FSW_NOCC", 0),
    ("fsubp st1,st0",               "ALL", "0", "fsubp st(1), st(0)",        "FSW_NOCC", 0),
    ("fsubr st0,st2",               "ALL", "0", "fsubr st(0), st(2)",        "FSW_NOCC", 0),
    ("fsubrp st1,st0",              "ALL", "0", "fsubrp st(1), st(0)",       "FSW_NOCC", 0),
    ("fsub qword [rdi]",            "ALL", "0", "fsub qword ptr [rdi]",      "FSW_NOCC", 0),
    ("fsubr dword [rdi]",           "ALL", "0", "fsubr dword ptr [rdi]",     "FSW_NOCC", 0),
    ("fisub word [rdi]",            "ALL", "0", "fisub word ptr [rdi]",      "FSW_NOCC", 0),
    ("fmul st0,st1",                "ALL", "0", "fmul st(0), st(1)",         "FSW_NOCC", 0),
    ("fmul st1,st0",                "ALL", "0", "fmul st(1), st(0)",         "FSW_NOCC", 0),
    ("fmulp st1,st0",               "ALL", "0", "fmulp st(1), st(0)",        "FSW_NOCC", 0),
    ("fmul qword [rdi]",            "ALL", "0", "fmul qword ptr [rdi]",      "FSW_NOCC", 0),
    ("fimul dword [rdi]",           "ALL", "0", "fimul dword ptr [rdi]",     "FSW_NOCC", 0),
    ("fdiv st0,st1",                "ALL", "0", "fdiv st(0), st(1)",         "FSW_NOCC", 0),
    ("fdivp st1,st0",               "ALL", "0", "fdivp st(1), st(0)",        "FSW_NOCC", 0),
    ("fdivr st0,st1",               "ALL", "0", "fdivr st(0), st(1)",        "FSW_NOCC", 0),
    ("fdivrp st1,st0",              "ALL", "0", "fdivrp st(1), st(0)",       "FSW_NOCC", 0),
    ("fdiv qword [rdi]",            "ALL", "0", "fdiv qword ptr [rdi]",      "FSW_NOCC", 0),
    ("fidiv dword [rdi]",           "ALL", "0", "fidiv dword ptr [rdi]",     "FSW_NOCC", 0),
    ("fidivr word [rdi]",           "ALL", "0", "fidivr word ptr [rdi]",     "FSW_NOCC", 0),
    ("fchs",                        "ALL", "0", "fchs",                      "FSW_NOCC", 0),
    ("fabs",                        "ALL", "0", "fabs",                      "FSW_NOCC", 0),
    ("fsqrt",                       "ALL", "0", "fsqrt",                     "FSW_NOCC", 0),
    ("fabs; fsqrt",                 "ALL", "0", "fabs\n fsqrt",               "FSW_NOCC", 0),
    ("frndint",                     "ALL", "0", "frndint",                   "FSW_NOCC", 0),
    ("fscale",                      "ALL", "0", "fscale",                    "FSW_NOCC", 0),
    ("fprem",                       "ALL", "0", "fprem",                     "FSW_ALL", 0),
    ("fprem1",                      "ALL", "0", "fprem1",                    "FSW_ALL", 0),
    ("fxtract",                     "ALL", "0", "fxtract",                   "FSW_NOCC", 0),
    ("fcom st1",                    "ALL", "0", "fcom st(1)",                "FSW_ALL", 0),
    ("fcom st0 (equal)",            "ALL", "0", "fcom st(0)",                "FSW_ALL", 0),
    ("fcomp st2",                   "ALL", "0", "fcomp st(2)",               "FSW_ALL", 0),
    ("fcompp",                      "ALL", "0", "fcompp",                    "FSW_ALL", 0),
    ("fucom st1",                   "ALL", "0", "fucom st(1)",               "FSW_ALL", 0),
    ("fucomp st1",                  "ALL", "0", "fucomp st(1)",              "FSW_ALL", 0),
    ("fucompp",                     "ALL", "0", "fucompp",                   "FSW_ALL", 0),
    ("fcom qword [rdi]",            "ALL", "0", "fcom qword ptr [rdi]",      "FSW_ALL", 0),
    ("ficomp dword [rdi]",          "ALL", "0", "ficomp dword ptr [rdi]",    "FSW_ALL", 0),
    ("fcomi st0,st1",               "ALL", "0", "fcomi st(0), st(1)",        "FSW_ALL", 0),
    ("fcomip st0,st2",              "ALL", "0", "fcomip st(0), st(2)",       "FSW_ALL", 0),
    ("fucomi st0,st1",              "ALL", "0", "fucomi st(0), st(1)",       "FSW_ALL", 0),
    ("fucomip st0,st1",             "ALL", "0", "fucomip st(0), st(1)",      "FSW_ALL", 0),
    ("fld qword [rdi]; fucomi (soup)", "ALL", "0", "fld qword ptr [rdi]\n fucomi st(0), st(1)", "FSW_ALL", 0),
    ("fld qword [rdi]; fcomi (soup)",  "ALL", "0", "fld qword ptr [rdi]\n fcomi st(0), st(1)",  "FSW_ALL", 0),
    ("ftst",                        "ALL", "0", "ftst",                      "FSW_ALL", 0),
    ("fxam",                        "ALL", "0", "fxam",                      "FSW_ALL", 0),
    ("fld qword [rdi]; fxam (soup)","ALL", "0", "fld qword ptr [rdi]\n fxam", "FSW_ALL", 0),
    ("ffree st2; fxam st2 via fxch","ALL", "0", "ffree st(2)\n fxch st(2)\n fxam", "FSW_ALL", 0),
    ("fcmovb st0,st1",              "ALL", "0", "fcmovb st(0), st(1)",       "FSW_NOCC", 0),
    ("fcmovne st0,st2",             "ALL", "0", "fcmovne st(0), st(2)",      "FSW_NOCC", 0),
    ("fcmovnbe st0,st1",            "ALL", "0", "fcmovnbe st(0), st(1)",     "FSW_NOCC", 0),
    ("fcmovu st0,st1",              "ALL", "0", "fcmovu st(0), st(1)",       "FSW_NOCC", 0),
    ("fnstcw [rdi]",                "ALL", "0", "fnstcw [rdi]",              "FSW_ALL", 0),
    ("fnstsw ax",                   "ALL", "0", "fnstsw ax",                 "FSW_ALL", 0),
    ("fnstsw [rdi]",                "ALL", "0", "fnstsw [rdi]",              "FSW_ALL", 0),
    ("fldcw pc=24; fdiv",           "ALL", "0", "mov word ptr [rdi], 0x007F\n fldcw [rdi]\n fdiv st(0), st(1)",  "FSW_NOCC", 0),
    ("fldcw pc=53; fmul",           "ALL", "0", "mov word ptr [rdi], 0x027F\n fldcw [rdi]\n fmul st(0), st(1)",  "FSW_NOCC", 0),
    ("fldcw rc=down; fistp",        "ALL", "0", "mov word ptr [rdi], 0x077F\n fldcw [rdi]\n fistp dword ptr [rdi+8]", "FSW_NOCC", 0),
    ("fldcw rc=zero; frndint",      "ALL", "0", "mov word ptr [rdi], 0x0F7F\n fldcw [rdi]\n frndint", "FSW_NOCC", 0),
    ("fldcw rc=up; fadd",           "ALL", "0", "mov word ptr [rdi], 0x0B7F\n fldcw [rdi]\n fadd st(0), st(1)", "FSW_NOCC", 0),
    ("fnclex",                      "ALL", "0", "fnclex",                    "FSW_ALL", 0),
    ("fninit",                      "ALL", "0", "fninit",                    "FSW_ALL", 0),
    ("fincstp; fdecstp",            "ALL", "0", "fincstp\n fdecstp",          "FSW_ALL", 0),
    ("fincstp",                     "ALL", "0", "fincstp",                   "FSW_ALL", 0),
    ("ffree st1",                   "ALL", "0", "ffree st(1)",               "FSW_ALL", 0),
    ("fld1 x8 (stack overflow)",    "ALL", "0", "fld1\n fld1\n fld1\n fld1\n fld1\n fld1\n fld1\n fld1", "FSW_ALL", 0),
    ("fstp x7 (stack underflow)",   "ALL", "0", "fstp st(0)\n fstp st(0)\n fstp st(0)\n fstp st(0)\n fstp st(0)\n fstp st(0)\n fstp st(0)", "FSW_ALL", 0),
    ("fnstenv/fldenv [rdi]",        "ALL", "0", "fnstenv [rdi]\n fldenv [rdi]", "FSW_ALL", 0),
    ("fnstenv [rdi]",               "ALL", "0", "fnstenv [rdi]",             "FSW_ALL", 0),
    ("fnsave/frstor [rdi]",         "ALL", "0", "fnsave [rdi]\n frstor [rdi]",  "FSW_ALL", 0),
    ("fxsave/fxrstor [rdi]",        "ALL", "0", "fxsave [rdi]\n fxrstor [rdi]", "FSW_ALL", 0),
    ("fsin",                        "ALL", "0", "fsin",                      "FSW_TOP", 1),
    ("fcos",                        "ALL", "0", "fcos",                      "FSW_TOP", 1),
    ("fsincos",                     "ALL", "0", "fsincos",                   "FSW_TOP", 1),
    ("fptan",                       "ALL", "0", "fptan",                     "FSW_TOP", 1),
    ("fpatan",                      "ALL", "0", "fpatan",                    "FSW_TOP", 1),
    ("fabs; fyl2x",                 "ALL", "0", "fabs\n fyl2x",               "FSW_TOP", 1),
    ("fabs; fyl2xp1",               "ALL", "0", "fabs\n fdiv st(0), st(0)\n fyl2xp1", "FSW_TOP", 1),   # x/x = 1 -> log2(2)
    ("f2xm1 (small)",               "ALL", "0", "fld1\n fdiv st(0), st(1)\n f2xm1", "FSW_TOP", 1),      # 1/x in (-1,1) mostly
]

def assemble(asm):
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "t.s"); obj = os.path.join(d, "t.o"); bin_ = os.path.join(d, "t.bin")
        with open(src, "w") as f:
            f.write(".intel_syntax noprefix\n.text\n" + asm + "\n")
        subprocess.check_call(["as", "--64", "-o", obj, src])
        subprocess.check_call(["objcopy", "-O", "binary", "-j", ".text", obj, bin_])
        return open(bin_, "rb").read()

def main():
    out = [f"/* GENERATED by cases_gen.py -- edit CASES there, not this file. */"]
    for case in CASES:
        name, mask, setup, asm = case[:4]
        code = assemble(asm)
        bytes_ = ",".join("0x%02X" % b for b in code)
        cmt = asm.replace(chr(10), "; ")
        if len(case) == 6:
            out.append(f'    TX("{name}", {mask}, {case[4]}, {case[5]}, {setup}, {bytes_}),   /* {cmt} */')
        else:
            out.append(f'    T("{name}", {mask}, {setup}, {bytes_}),   /* {cmt} */')
    path = os.path.join(HERE, "cases_gen.inc")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"{len(CASES)} cases -> {path}")

if __name__ == "__main__":
    main()
