/* What a fault inside compiled code reports, against what it should report.
 *
 * The dynarec keeps guest registers in host registers and writes them back at
 * block boundaries, so a fault in the middle of a block has no consistent
 * guest state to report -- unless something reconstructs it. It does: every
 * guest memory access carries an out-of-line recovery stub holding the spill
 * sequence for that point in the block, and a host SIGSEGV at one of those
 * instructions becomes a jump to its stub (see the fault-recovery section of
 * core/src/jit/jit.c).
 *
 * That is only worth anything if the state it produces is the state the guest
 * actually had, so this does not check that recovery "succeeds". x86 says a
 * faulting instruction has no effect -- including a faulting push, which
 * leaves the stack pointer alone -- so the architectural state at a fault is
 * exactly the state after the instruction before it. That is the oracle, and
 * it is one the interpreter can produce without faulting at all: run it with
 * a step budget one short of the faulting instruction, and compare every
 * guest register, every XMM, the flags, the whole x87 stack and tag word, the
 * reported RIP and guest memory against what the dynarec's recovery says.
 *
 * Stating it that way is better than running both paths into the fault and
 * diffing them. It is a claim about x86 rather than about agreement, so two
 * implementations cannot be wrong together; and the interpreter never touches
 * the bad page, which keeps the test's own signal handling down to the one
 * case it is actually about.
 *
 * The sequences (tests/difftest/faultcases_gen.inc, generated by
 * tools/gen/faultcases.sh from real assembly, each carrying its own
 * disassembly) put as much state as possible in host registers before
 * faulting: dirty GPRs, dirty XMMs, a loaded x87 stack, a stack pointer the
 * lowering has already moved, a register cache a callout has just
 * invalidated.
 *
 * On hosts without a dynarec the test passes trivially.
 */
#define _GNU_SOURCE
#include "xcore/cpu.h"

#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>

#include "xcore/hostpc.h"

#define B(...) ((const uint8_t[]){ __VA_ARGS__ })
typedef struct { const char *name; int x87; int before; const uint8_t *code; size_t len; } faultcase;
#include "difftest/faultcases_gen.inc"
#define NCASES (sizeof FAULTCASES / sizeof FAULTCASES[0])

/* Guest memory: a readable page of data, a stack, the code, and -- the point
 * of the exercise -- a page mapped PROT_NONE, so touching it is a real fault
 * at a known address rather than a lucky accident. The hole has mapped pages
 * on both sides, so a stack can be walked *into* it: the cases that push
 * twice need the first push to land somewhere real. */
static uint8_t *g_data, *g_stack, *g_code, *g_hole, *g_above;
enum { DATA_SIZE = 4096, STACK_SIZE = 65536, CODE_SIZE = 4096, HOLE_SIZE = 4096 };

static xc_cpu *g_cpu;
static sigjmp_buf g_jmp;
static volatile int g_armed;
static volatile int g_via_stub;          /* the last run was recovered through a stub */
static volatile int g_via_jmp;           /* ... or through the interpreter, from a callout */

/* Same plumbing as the runtime's, from the same header, so the two cannot
 * disagree about how to read or move a signal context's PC. */

/* Two cases, the same two winrun has. A compiled block reaching for the hole
 * goes to its recovery stub. An instruction the dynarec does not lower is run
 * by the interpreter through a callout, which spills first -- so the fault
 * arrives with the cpu struct already consistent and can be left through
 * siglongjmp. A fault anywhere else is a bug in this test or in the core, and
 * swallowing it would hide exactly what the test exists to find. */
static void on_segv(int sig, siginfo_t *si, void *uctx) {
    uint64_t addr = (uint64_t)(uintptr_t)si->si_addr;
    uint64_t hole = (uint64_t)(uintptr_t)g_hole;
    uint64_t pc = XC_HOST_PC(uctx);
    uint64_t lo = 0, hi = 0;
    int in_jit = pc && xc_jit_code_range(&lo, &hi) && pc >= lo && pc < hi;
    if (g_armed && in_jit && addr >= hole && addr < hole + HOLE_SIZE) {
        uint64_t grip = 0;
        void *stub = xc_jit_fault_stub(pc, &grip);
        if (stub && XC_HAVE_HOST_PC_SET) {
            g_cpu->stop = XC_STOP_FAULT;
            g_cpu->fault_kind = XC_FAULT_MEM;
            g_cpu->fault_addr = addr;
            g_cpu->rip = grip;
            g_via_stub = 1;
            XC_HOST_PC_SET(uctx, (uint64_t)(uintptr_t)stub);
            return;
        }
    }
    if (g_armed && !in_jit && addr >= hole && addr < hole + HOLE_SIZE) {
        g_cpu->stop = XC_STOP_FAULT;
        g_cpu->fault_kind = XC_FAULT_MEM;
        g_cpu->fault_addr = addr;
        g_via_jmp = 1;
        g_armed = 0;
        siglongjmp(g_jmp, 1);
    }
    signal(sig, SIG_DFL);
    raise(sig);
}

/* xorshift, the same generator the other differential tests use */
static uint64_t xs(uint64_t *s) { uint64_t x = *s; x ^= x << 13; x ^= x >> 7; x ^= x << 17; return *s = x; }

typedef struct {
    uint64_t gpr[16], rflags, rip, fault_addr;
    xc_u128 xmm[16];
    uint32_t mxcsr; xc_stop st; xc_fault kind;
    xc_f80 fpr[8]; uint16_t fcw, fsw; uint8_t ftag;
    uint8_t data[256], stack[512], above[64];
} result;

/* `steps` short of the whole sequence runs the interpreter to the oracle
 * state; the full sequence through the dynarec runs into the fault. */
static void run(const faultcase *t, uint64_t seed, int jit, uint64_t steps, result *r) {
    uint64_t s = seed * 7 + 3;
    for (size_t i = 0; i < DATA_SIZE; i += 8) { uint64_t v = xs(&s); memcpy(g_data + i, &v, 8); }
    for (size_t i = 0; i < STACK_SIZE; i += 8) { uint64_t v = xs(&s); memcpy(g_stack + i, &v, 8); }
    for (size_t i = 0; i < 64; i += 8) { uint64_t v = xs(&s); memcpy(g_above + i, &v, 8); }
    /* readable doubles for the x87 cases, which load before they fault */
    for (int i = 0; i < 8; i++) {
        double d = (double)(int64_t)(xs(&s) % 20001) / 16.0 - 625.0;
        memcpy(g_data + 8 * i, &d, 8);
    }
    memset(g_code, 0xCC, CODE_SIZE);
    memcpy(g_code, t->code, t->len);

    xc_mem mem; xc_mem_init_identity(&mem);
    xc_cpu c; xc_cpu_init(&c, XC_MODE_64, &mem);
    uint64_t rs = seed | 1;
    for (int i = 0; i < 16; i++) c.gpr[i] = xs(&rs);
    c.gpr[XC_RSP] = (uint64_t)(uintptr_t)(g_stack + STACK_SIZE - 256);
    c.gpr[XC_RDI] = (uint64_t)(uintptr_t)g_data;
    c.gpr[XC_RSI] = (uint64_t)(uintptr_t)g_data + 64;
    c.gpr[XC_R15] = (uint64_t)(uintptr_t)g_hole + 64;      /* inside the hole: what the cases fault on */
    c.gpr[XC_R14] = (uint64_t)(uintptr_t)g_above + 8;      /* just above it, so a stack can walk in */
    c.rflags = 0x202 | (xs(&rs) & XC_ARITH_FLAGS);
    uint64_t x = seed ^ 0xA5A5A5A5A5A5A5A5ull;
    for (int i = 0; i < 16; i++) {
        double a = (double)(int64_t)(xs(&x) % 20001) / 8.0 - 1250.0;
        double b = (double)(int64_t)(xs(&x) % 20001) / 16.0 - 625.0;
        memcpy(&c.xmm[i].lo, &a, 8); memcpy(&c.xmm[i].hi, &b, 8);
    }
    c.rip = (uint64_t)(uintptr_t)g_code;

    g_cpu = &c;
    xc_jit_enable(jit);
    g_via_stub = 0; g_via_jmp = 0;
    if (sigsetjmp(g_jmp, 1) == 0) {
        g_armed = 1;
        r->st = xc_run(&c, steps);
        g_armed = 0;
    } else {
        r->st = XC_STOP_FAULT;             /* the interpreter's own access, from a callout */
    }
    xc_flags_sync(&c);              /* the documented contract: lazy until asked */
    r->rip = c.rip; r->fault_addr = c.fault_addr; r->kind = c.fault_kind;
    memcpy(r->gpr, c.gpr, sizeof r->gpr); r->rflags = c.rflags;
    memcpy(r->xmm, c.xmm, sizeof r->xmm); r->mxcsr = c.mxcsr;
    memcpy(r->fpr, c.fpr, sizeof r->fpr); r->fcw = c.fcw; r->fsw = c.fsw; r->ftag = c.ftag_empty;
    memcpy(r->data, g_data, sizeof r->data);
    memcpy(r->stack, g_stack + STACK_SIZE - sizeof r->stack, sizeof r->stack);
    memcpy(r->above, g_above, sizeof r->above);
}

static uint8_t *claim(size_t n, int prot) {
    void *p = mmap(0, n, prot, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
    if (p == MAP_FAILED) { perror("mmap"); exit(2); }
    return (uint8_t *)p;
}

int main(int argc, char **argv) {
    int seeds = argc > 1 ? atoi(argv[1]) : 8;
    setvbuf(stdout, 0, _IONBF, 0);
    if (!xc_jit_available()) { puts("test_faultdiff: no JIT on this host, nothing to compare"); return 0; }

    g_data = claim(DATA_SIZE, PROT_READ | PROT_WRITE);
    g_stack = claim(STACK_SIZE, PROT_READ | PROT_WRITE);
    g_code = claim(CODE_SIZE, PROT_READ | PROT_WRITE);
    /* three pages, with the middle one taken away */
    uint8_t *span = claim(3 * HOLE_SIZE, PROT_READ | PROT_WRITE);
    g_hole = span + HOLE_SIZE;
    g_above = span + 2 * HOLE_SIZE;
    if (mprotect(g_hole, HOLE_SIZE, PROT_NONE) != 0) { perror("mprotect"); return 2; }

    if (getenv("FAULTDIFF_TRACE"))
        printf("data %p stack %p code %p hole %p\n", (void*)g_data, (void*)g_stack, (void*)g_code, (void*)g_hole);
    struct sigaction sa; memset(&sa, 0, sizeof sa);
    sa.sa_sigaction = on_segv; sa.sa_flags = SA_SIGINFO;
    sigaction(SIGSEGV, &sa, 0); sigaction(SIGBUS, &sa, 0);

    int bad = 0, runs = 0, recovered = 0, via_interp = 0;
    for (size_t i = 0; i < NCASES; i++) {
        const faultcase *t = &FAULTCASES[i];
        const char *only = getenv("FAULTDIFF_ONLY");
        if (only && strcmp(only, t->name)) continue;
        for (int sd = 0; sd < seeds; sd++) {
            result a, b;
            uint64_t seed = (uint64_t)sd * 1000003u + i * 31 + 1;
            if (getenv("FAULTDIFF_TRACE")) printf("case %s seed %d oracle\n", t->name, sd);
            run(t, seed, 0, (uint64_t)t->before, &a);      /* interpreter, one instruction short */
            if (getenv("FAULTDIFF_TRACE")) printf("case %s seed %d jit\n", t->name, sd);
            run(t, seed, 1, 1000, &b);                     /* dynarec, into the fault */
            if (g_via_stub) recovered++;
            if (g_via_jmp) via_interp++;
            runs++;
            int fail = 0;
            #define BAD(...) do { printf("  [%s] seed %d: ", t->name, sd); printf(__VA_ARGS__); fail = 1; } while (0)
            if (a.st != XC_STOP_STEPS) BAD("the oracle run stopped early (%s) -- the case is wrong\n", xc_stop_name(a.st));
            if (b.st != XC_STOP_FAULT) BAD("the dynarec did not report a fault (%s)\n", xc_stop_name(b.st));
            if (!g_via_stub && !g_via_jmp) BAD("the fault came back through neither path\n");
            if (b.fault_addr != (uint64_t)(uintptr_t)g_hole + 64 && b.fault_addr < (uint64_t)(uintptr_t)g_hole)
                BAD("fault address %#llx is not in the hole\n", (unsigned long long)b.fault_addr);
            if (a.rip != b.rip) BAD("rip %#llx vs jit %#llx (+%lld vs +%lld into the code)\n",
                                    (unsigned long long)a.rip, (unsigned long long)b.rip,
                                    (long long)(a.rip - (uint64_t)(uintptr_t)g_code),
                                    (long long)(b.rip - (uint64_t)(uintptr_t)g_code));
            for (int g = 0; g < 16; g++) if (a.gpr[g] != b.gpr[g])
                BAD("gpr%d %#llx vs jit %#llx\n", g, (unsigned long long)a.gpr[g], (unsigned long long)b.gpr[g]);
            if ((a.rflags & XC_ARITH_FLAGS) != (b.rflags & XC_ARITH_FLAGS))
                BAD("rflags %#llx vs jit %#llx\n", (unsigned long long)a.rflags, (unsigned long long)b.rflags);
            for (int x = 0; x < 16; x++) if (a.xmm[x].lo != b.xmm[x].lo || a.xmm[x].hi != b.xmm[x].hi)
                BAD("xmm%d %016llx%016llx vs jit %016llx%016llx\n", x,
                    (unsigned long long)a.xmm[x].hi, (unsigned long long)a.xmm[x].lo,
                    (unsigned long long)b.xmm[x].hi, (unsigned long long)b.xmm[x].lo);
            /* DE (denormal operand) is the one MXCSR bit the native path does not track */
            if ((a.mxcsr & ~2u) != (b.mxcsr & ~2u)) BAD("mxcsr %#x vs jit %#x\n", a.mxcsr, b.mxcsr);
            if (a.fcw != b.fcw || (a.fsw & ~2u) != (b.fsw & ~2u) || a.ftag != b.ftag)
                BAD("x87 control state: fcw %#x/%#x fsw %#x/%#x ftag %#x/%#x\n",
                    a.fcw, b.fcw, a.fsw, b.fsw, a.ftag, b.ftag);
            for (int k = 0; k < 8; k++) if (a.fpr[k].mant != b.fpr[k].mant || a.fpr[k].se != b.fpr[k].se)
                BAD("st(%d) %04x.%016llx vs jit %04x.%016llx\n", k, a.fpr[k].se,
                    (unsigned long long)a.fpr[k].mant, b.fpr[k].se, (unsigned long long)b.fpr[k].mant);
            if (memcmp(a.data, b.data, sizeof a.data)) BAD("guest data memory differs\n");
            if (memcmp(a.stack, b.stack, sizeof a.stack)) BAD("guest stack memory differs\n");
            if (memcmp(a.above, b.above, sizeof a.above)) BAD("memory above the hole differs\n");
            #undef BAD
            bad += fail != 0;
        }
    }
    printf("test_faultdiff: %zu cases x %d seeds = %d runs, %d failed; %d recovered through a stub, "
           "%d through an interpreter callout, %llu sites registered\n",
           NCASES, seeds, runs, bad, recovered, via_interp, (unsigned long long)xc_jit_fault_sites());
    if (!bad && !recovered) { puts("test_faultdiff: nothing went through a recovery stub -- the test proved nothing"); return 1; }
    return bad ? 1 : 0;
}
