/* Choosing a face for a LOGFONT, and getting glyphs out of it.
 *
 * gdi32 asks for text by (face name, height, weight, italic); this turns that
 * into one of the built-in faces at a pixel size, and hands back rasterized
 * glyphs and the metrics a caller needs to lay them out.
 *
 * There used to be a stroke font here -- polylines on a design grid -- for
 * the reason its comment gave: there is no font file to load on an iPhone,
 * shipping a bitmap font locks the text to one size, and a dialog asks for
 * whatever size its template says. Real outlines answer all three without the
 * drawback, because the font is *compiled in* (win32/fontdata.c): there is no
 * file to find, it scales to any size, and the same bytes are rasterized by
 * the same integer code on a Linux runner, under qemu and on a phone -- which
 * is what lets a frame containing text still be checked by checksum.
 */
#ifndef W32_GDIFONT_H
#define W32_GDIFONT_H
#include <stdint.h>
#include "truetype.h"

/* The fonts themselves (win32/fontdata.c, generated by tools/mkfont). */
extern const unsigned char w32_font_sans[];       extern const unsigned int w32_font_sans_len;
extern const unsigned char w32_font_sans_bold[];  extern const unsigned int w32_font_sans_bold_len;
extern const unsigned char w32_font_mono[];       extern const unsigned int w32_font_mono_len;

/* A chosen face at a chosen size. Metrics are in pixels except `advance`,
 * which is 26.6 so a run of text accumulates without drifting a pixel every
 * ten characters. */
typedef struct {
    tt_face *tt;
    int px;                 /* em size in pixels */
    int ascent, descent;    /* above and below the baseline, both positive */
    int height;             /* ascent + descent: GDI's tmHeight */
    int oblique, embolden;  /* synthesised italic / bold */
    int fixed;              /* this face is monospaced */
} gf_font;

/* Pick a face. `height` follows LOGFONT: negative is the em size, positive is
 * the cell height, zero means the shell's default. Never fails -- there is
 * always a built-in face -- so callers have nothing to check. */
void gf_select(gf_font *out, const char *face, int height, int weight,
               int italic, int fixed_pitch);

/* How far the pen moves after `ch`, in 26.6 pixels. */
int gf_advance(const gf_font *f, uint32_t ch);

/* The glyph, rasterized, or NULL for a character with nothing to draw (a
 * space, or one the font does not have). */
const tt_glyph *gf_glyph(const gf_font *f, uint32_t ch);

/* The mean of 'A'-'Z' and 'a'-'z', in whole pixels: the number every dialog
 * template's unit conversion is defined in terms of. */
int gf_average_width(const gf_font *f);

#endif
