/* Generated by tools/gen/vtables.sh from mingw-w64 headers -- do not edit.
 *
 * COM vtable slot numbers. The order is the ABI: a table built with one
 * slot out calls whatever is next in it, which compiles, links, and runs
 * wrong. Indexing by these names instead of by literal numbers means the
 * order comes from the header rather than from counting.
 */
#ifndef W32_VTABLES_GEN_H
#define W32_VTABLES_GEN_H

/* IDirectSound8 -- 12 slots */
enum {
    DS8_QueryInterface = 0,
    DS8_AddRef = 1,
    DS8_Release = 2,
    DS8_CreateSoundBuffer = 3,
    DS8_GetCaps = 4,
    DS8_DuplicateSoundBuffer = 5,
    DS8_SetCooperativeLevel = 6,
    DS8_Compact = 7,
    DS8_GetSpeakerConfig = 8,
    DS8_SetSpeakerConfig = 9,
    DS8_Initialize = 10,
    DS8_VerifyCertification = 11,
    DS8_NSLOTS = 12,
};

/* IDirectSoundBuffer8 -- 24 slots */
enum {
    DSB8_QueryInterface = 0,
    DSB8_AddRef = 1,
    DSB8_Release = 2,
    DSB8_GetCaps = 3,
    DSB8_GetCurrentPosition = 4,
    DSB8_GetFormat = 5,
    DSB8_GetVolume = 6,
    DSB8_GetPan = 7,
    DSB8_GetFrequency = 8,
    DSB8_GetStatus = 9,
    DSB8_Initialize = 10,
    DSB8_Lock = 11,
    DSB8_Play = 12,
    DSB8_SetCurrentPosition = 13,
    DSB8_SetFormat = 14,
    DSB8_SetVolume = 15,
    DSB8_SetPan = 16,
    DSB8_SetFrequency = 17,
    DSB8_Stop = 18,
    DSB8_Unlock = 19,
    DSB8_Restore = 20,
    DSB8_SetFX = 21,
    DSB8_AcquireResources = 22,
    DSB8_GetObjectInPath = 23,
    DSB8_NSLOTS = 24,
};

/* IDirectSound3DListener -- 18 slots */
enum {
    DS3L_QueryInterface = 0,
    DS3L_AddRef = 1,
    DS3L_Release = 2,
    DS3L_GetAllParameters = 3,
    DS3L_GetDistanceFactor = 4,
    DS3L_GetDopplerFactor = 5,
    DS3L_GetOrientation = 6,
    DS3L_GetPosition = 7,
    DS3L_GetRolloffFactor = 8,
    DS3L_GetVelocity = 9,
    DS3L_SetAllParameters = 10,
    DS3L_SetDistanceFactor = 11,
    DS3L_SetDopplerFactor = 12,
    DS3L_SetOrientation = 13,
    DS3L_SetPosition = 14,
    DS3L_SetRolloffFactor = 15,
    DS3L_SetVelocity = 16,
    DS3L_CommitDeferredSettings = 17,
    DS3L_NSLOTS = 18,
};

/* IDirectSound3DBuffer -- 21 slots */
enum {
    DS3B_QueryInterface = 0,
    DS3B_AddRef = 1,
    DS3B_Release = 2,
    DS3B_GetAllParameters = 3,
    DS3B_GetConeAngles = 4,
    DS3B_GetConeOrientation = 5,
    DS3B_GetConeOutsideVolume = 6,
    DS3B_GetMaxDistance = 7,
    DS3B_GetMinDistance = 8,
    DS3B_GetMode = 9,
    DS3B_GetPosition = 10,
    DS3B_GetVelocity = 11,
    DS3B_SetAllParameters = 12,
    DS3B_SetConeAngles = 13,
    DS3B_SetConeOrientation = 14,
    DS3B_SetConeOutsideVolume = 15,
    DS3B_SetMaxDistance = 16,
    DS3B_SetMinDistance = 17,
    DS3B_SetMode = 18,
    DS3B_SetPosition = 19,
    DS3B_SetVelocity = 20,
    DS3B_NSLOTS = 21,
};

/* IDirectSoundNotify -- 4 slots */
enum {
    DSN_QueryInterface = 0,
    DSN_AddRef = 1,
    DSN_Release = 2,
    DSN_SetNotificationPositions = 3,
    DSN_NSLOTS = 4,
};

/* IDirectSoundCapture -- 6 slots */
enum {
    DSC_QueryInterface = 0,
    DSC_AddRef = 1,
    DSC_Release = 2,
    DSC_CreateCaptureBuffer = 3,
    DSC_GetCaps = 4,
    DSC_Initialize = 5,
    DSC_NSLOTS = 6,
};

/* IDirectSoundCaptureBuffer8 -- 14 slots */
enum {
    DSCB8_QueryInterface = 0,
    DSCB8_AddRef = 1,
    DSCB8_Release = 2,
    DSCB8_GetCaps = 3,
    DSCB8_GetCurrentPosition = 4,
    DSCB8_GetFormat = 5,
    DSCB8_GetStatus = 6,
    DSCB8_Initialize = 7,
    DSCB8_Lock = 8,
    DSCB8_Start = 9,
    DSCB8_Stop = 10,
    DSCB8_Unlock = 11,
    DSCB8_GetObjectInPath = 12,
    DSCB8_GetFXStatus = 13,
    DSCB8_NSLOTS = 14,
};

/* IDirectInput8W -- 11 slots */
enum {
    DI8_QueryInterface = 0,
    DI8_AddRef = 1,
    DI8_Release = 2,
    DI8_CreateDevice = 3,
    DI8_EnumDevices = 4,
    DI8_GetDeviceStatus = 5,
    DI8_RunControlPanel = 6,
    DI8_Initialize = 7,
    DI8_FindDevice = 8,
    DI8_EnumDevicesBySemantics = 9,
    DI8_ConfigureDevices = 10,
    DI8_NSLOTS = 11,
};

/* IDirectInput7W -- 10 slots */
enum {
    DI7_QueryInterface = 0,
    DI7_AddRef = 1,
    DI7_Release = 2,
    DI7_CreateDevice = 3,
    DI7_EnumDevices = 4,
    DI7_GetDeviceStatus = 5,
    DI7_RunControlPanel = 6,
    DI7_Initialize = 7,
    DI7_FindDevice = 8,
    DI7_CreateDeviceEx = 9,
    DI7_NSLOTS = 10,
};

/* IDirectInputDevice8W -- 32 slots */
enum {
    DID8_QueryInterface = 0,
    DID8_AddRef = 1,
    DID8_Release = 2,
    DID8_GetCapabilities = 3,
    DID8_EnumObjects = 4,
    DID8_GetProperty = 5,
    DID8_SetProperty = 6,
    DID8_Acquire = 7,
    DID8_Unacquire = 8,
    DID8_GetDeviceState = 9,
    DID8_GetDeviceData = 10,
    DID8_SetDataFormat = 11,
    DID8_SetEventNotification = 12,
    DID8_SetCooperativeLevel = 13,
    DID8_GetObjectInfo = 14,
    DID8_GetDeviceInfo = 15,
    DID8_RunControlPanel = 16,
    DID8_Initialize = 17,
    DID8_CreateEffect = 18,
    DID8_EnumEffects = 19,
    DID8_GetEffectInfo = 20,
    DID8_GetForceFeedbackState = 21,
    DID8_SendForceFeedbackCommand = 22,
    DID8_EnumCreatedEffectObjects = 23,
    DID8_Escape = 24,
    DID8_Poll = 25,
    DID8_SendDeviceData = 26,
    DID8_EnumEffectsInFile = 27,
    DID8_WriteEffectToFile = 28,
    DID8_BuildActionMap = 29,
    DID8_SetActionMap = 30,
    DID8_GetImageInfo = 31,
    DID8_NSLOTS = 32,
};

/* IDirectInputDevice7W -- 29 slots */
enum {
    DID7_QueryInterface = 0,
    DID7_AddRef = 1,
    DID7_Release = 2,
    DID7_GetCapabilities = 3,
    DID7_EnumObjects = 4,
    DID7_GetProperty = 5,
    DID7_SetProperty = 6,
    DID7_Acquire = 7,
    DID7_Unacquire = 8,
    DID7_GetDeviceState = 9,
    DID7_GetDeviceData = 10,
    DID7_SetDataFormat = 11,
    DID7_SetEventNotification = 12,
    DID7_SetCooperativeLevel = 13,
    DID7_GetObjectInfo = 14,
    DID7_GetDeviceInfo = 15,
    DID7_RunControlPanel = 16,
    DID7_Initialize = 17,
    DID7_CreateEffect = 18,
    DID7_EnumEffects = 19,
    DID7_GetEffectInfo = 20,
    DID7_GetForceFeedbackState = 21,
    DID7_SendForceFeedbackCommand = 22,
    DID7_EnumCreatedEffectObjects = 23,
    DID7_Escape = 24,
    DID7_Poll = 25,
    DID7_SendDeviceData = 26,
    DID7_EnumEffectsInFile = 27,
    DID7_WriteEffectToFile = 28,
    DID7_NSLOTS = 29,
};

#endif
