/* Generated by tools/gen/vtables.sh from mingw-w64 headers -- do not edit.
 *
 * COM vtable slot numbers. The order is the ABI: a table built with one
 * slot out calls whatever is next in it, which compiles, links, and runs
 * wrong. Indexing by these names instead of by literal numbers means the
 * order comes from the header rather than from counting.
 */
#ifndef W32_VTABLES_GEN_H
#define W32_VTABLES_GEN_H

/* IDirectSound8 -- 12 slots */
enum {
    DS8_QueryInterface = 0,
    DS8_AddRef = 1,
    DS8_Release = 2,
    DS8_CreateSoundBuffer = 3,
    DS8_GetCaps = 4,
    DS8_DuplicateSoundBuffer = 5,
    DS8_SetCooperativeLevel = 6,
    DS8_Compact = 7,
    DS8_GetSpeakerConfig = 8,
    DS8_SetSpeakerConfig = 9,
    DS8_Initialize = 10,
    DS8_VerifyCertification = 11,
    DS8_NSLOTS = 12,
};

/* IDirectSoundBuffer8 -- 24 slots */
enum {
    DSB8_QueryInterface = 0,
    DSB8_AddRef = 1,
    DSB8_Release = 2,
    DSB8_GetCaps = 3,
    DSB8_GetCurrentPosition = 4,
    DSB8_GetFormat = 5,
    DSB8_GetVolume = 6,
    DSB8_GetPan = 7,
    DSB8_GetFrequency = 8,
    DSB8_GetStatus = 9,
    DSB8_Initialize = 10,
    DSB8_Lock = 11,
    DSB8_Play = 12,
    DSB8_SetCurrentPosition = 13,
    DSB8_SetFormat = 14,
    DSB8_SetVolume = 15,
    DSB8_SetPan = 16,
    DSB8_SetFrequency = 17,
    DSB8_Stop = 18,
    DSB8_Unlock = 19,
    DSB8_Restore = 20,
    DSB8_SetFX = 21,
    DSB8_AcquireResources = 22,
    DSB8_GetObjectInPath = 23,
    DSB8_NSLOTS = 24,
};

/* IDirectSound3DListener -- 18 slots */
enum {
    DS3L_QueryInterface = 0,
    DS3L_AddRef = 1,
    DS3L_Release = 2,
    DS3L_GetAllParameters = 3,
    DS3L_GetDistanceFactor = 4,
    DS3L_GetDopplerFactor = 5,
    DS3L_GetOrientation = 6,
    DS3L_GetPosition = 7,
    DS3L_GetRolloffFactor = 8,
    DS3L_GetVelocity = 9,
    DS3L_SetAllParameters = 10,
    DS3L_SetDistanceFactor = 11,
    DS3L_SetDopplerFactor = 12,
    DS3L_SetOrientation = 13,
    DS3L_SetPosition = 14,
    DS3L_SetRolloffFactor = 15,
    DS3L_SetVelocity = 16,
    DS3L_CommitDeferredSettings = 17,
    DS3L_NSLOTS = 18,
};

/* IDirectSound3DBuffer -- 21 slots */
enum {
    DS3B_QueryInterface = 0,
    DS3B_AddRef = 1,
    DS3B_Release = 2,
    DS3B_GetAllParameters = 3,
    DS3B_GetConeAngles = 4,
    DS3B_GetConeOrientation = 5,
    DS3B_GetConeOutsideVolume = 6,
    DS3B_GetMaxDistance = 7,
    DS3B_GetMinDistance = 8,
    DS3B_GetMode = 9,
    DS3B_GetPosition = 10,
    DS3B_GetVelocity = 11,
    DS3B_SetAllParameters = 12,
    DS3B_SetConeAngles = 13,
    DS3B_SetConeOrientation = 14,
    DS3B_SetConeOutsideVolume = 15,
    DS3B_SetMaxDistance = 16,
    DS3B_SetMinDistance = 17,
    DS3B_SetMode = 18,
    DS3B_SetPosition = 19,
    DS3B_SetVelocity = 20,
    DS3B_NSLOTS = 21,
};

/* IDirectSoundNotify -- 4 slots */
enum {
    DSN_QueryInterface = 0,
    DSN_AddRef = 1,
    DSN_Release = 2,
    DSN_SetNotificationPositions = 3,
    DSN_NSLOTS = 4,
};

/* IDirectSoundCapture -- 6 slots */
enum {
    DSC_QueryInterface = 0,
    DSC_AddRef = 1,
    DSC_Release = 2,
    DSC_CreateCaptureBuffer = 3,
    DSC_GetCaps = 4,
    DSC_Initialize = 5,
    DSC_NSLOTS = 6,
};

/* IDirectSoundCaptureBuffer8 -- 14 slots */
enum {
    DSCB8_QueryInterface = 0,
    DSCB8_AddRef = 1,
    DSCB8_Release = 2,
    DSCB8_GetCaps = 3,
    DSCB8_GetCurrentPosition = 4,
    DSCB8_GetFormat = 5,
    DSCB8_GetStatus = 6,
    DSCB8_Initialize = 7,
    DSCB8_Lock = 8,
    DSCB8_Start = 9,
    DSCB8_Stop = 10,
    DSCB8_Unlock = 11,
    DSCB8_GetObjectInPath = 12,
    DSCB8_GetFXStatus = 13,
    DSCB8_NSLOTS = 14,
};

#endif
