/* XAudio2: the sound API of every game since 2008 or so.
 *
 * A game creates an engine, one mastering voice, and a source voice per
 * sound, then *submits buffers* to a source voice and is told through a
 * callback when each one has been played -- which is how it streams music
 * and knows when to hand over the next block. So the shape here is a queue
 * per voice, fed into audio_out's gapless two-block slot: the block playing
 * and the one behind it are the mixer's, the rest wait here, and at every
 * tick (a wait, or any call in) what the mixer has finished is popped and the
 * game's OnBufferEnd/OnLoopEnd/OnStreamEnd are called on the guest thread,
 * where the guest is.
 *
 * Two vtable layouts. 2.7 (xaudio2_7.dll, reached through CoCreateInstance
 * with one of the 2.x CLSIDs) has GetDeviceCount, GetDeviceDetails and
 * Initialize after Release, a two-argument GetState and no GetChannelMask;
 * 2.8 and 2.9 (XAudio2Create from xaudio2_8/9.dll) do not. The slot
 * numbers below come from Wine's xaudio2.idl -- the header is generated by
 * widl in a shape tools/gen/vtables.sh cannot read -- and the counts are
 * asserted against what that file declares.
 *
 * Not here: effects (APOs), submix routing beyond pass-through, output
 * matrices, filters, ADPCM/xWMA formats. Each answers with the documented
 * code or S_OK-and-nothing, never by pretending to have done something that
 * would be heard.
 */
#define _GNU_SOURCE
#include "w32.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

enum { S_OK_ = 0, E_FAIL_ = (int)0x80004005, E_NOTIMPL_ = (int)0x80004001, E_POINTER_ = (int)0x80004003,
       E_INVALIDARG_ = (int)0x80070057, XAUDIO2_E_INVALID_CALL_ = (int)0x88960001 };
enum { XAUDIO2_END_OF_STREAM_ = 0x40, XAUDIO2_LOOP_INFINITE_ = 255 };

/* IXAudio2 slots, from xaudio2.idl. */
enum { XA_QueryInterface = 0, XA_AddRef, XA_Release,
       /* 2.7 only */ XA7_GetDeviceCount, XA7_GetDeviceDetails, XA7_Initialize,
       XA7_RegisterForCallbacks, XA7_UnregisterForCallbacks, XA7_CreateSourceVoice, XA7_CreateSubmixVoice,
       XA7_CreateMasteringVoice, XA7_StartEngine, XA7_StopEngine, XA7_CommitChanges, XA7_GetPerformanceData,
       XA7_SetDebugConfiguration, XA7_NSLOTS };
enum { XA9_RegisterForCallbacks = 3, XA9_UnregisterForCallbacks, XA9_CreateSourceVoice, XA9_CreateSubmixVoice,
       XA9_CreateMasteringVoice, XA9_StartEngine, XA9_StopEngine, XA9_CommitChanges, XA9_GetPerformanceData,
       XA9_SetDebugConfiguration, XA9_NSLOTS };
_Static_assert(XA7_NSLOTS == 16 && XA9_NSLOTS == 13, "IXAudio2: 16 slots in 2.7, 13 in 2.8+");
/* IXAudio2Voice (no IUnknown), then what each kind adds. */
enum { XV_GetVoiceDetails = 0, XV_SetOutputVoices, XV_SetEffectChain, XV_EnableEffect, XV_DisableEffect, XV_GetEffectState,
       XV_SetEffectParameters, XV_GetEffectParameters, XV_SetFilterParameters, XV_GetFilterParameters,
       XV_SetOutputFilterParameters, XV_GetOutputFilterParameters, XV_SetVolume, XV_GetVolume, XV_SetChannelVolumes,
       XV_GetChannelVolumes, XV_SetOutputMatrix, XV_GetOutputMatrix, XV_DestroyVoice, XV_NSLOTS };
enum { XS_Start = XV_NSLOTS, XS_Stop, XS_SubmitSourceBuffer, XS_FlushSourceBuffers, XS_Discontinuity, XS_ExitLoop,
       XS_GetState, XS_SetFrequencyRatio, XS_GetFrequencyRatio, XS_SetSourceSampleRate, XS_NSLOTS };
enum { XM9_GetChannelMask = XV_NSLOTS, XM9_NSLOTS, XM7_NSLOTS = XV_NSLOTS };
_Static_assert(XV_NSLOTS == 19 && XS_NSLOTS == 29 && XM9_NSLOTS == 20, "XAudio2 voice slot counts, per xaudio2.idl");
/* IXAudio2VoiceCallback */
enum { CB_OnVoiceProcessingPassStart = 0, CB_OnVoiceProcessingPassEnd, CB_OnStreamEnd, CB_OnBufferStart, CB_OnBufferEnd,
       CB_OnLoopEnd, CB_OnVoiceError };

/* Engine fields, voice fields (64-bit slots) */
enum { E_VER = 0, E_RUNNING = 1, E_NFIELDS = 2 };
enum { V_KIND = 0, V_VER = 1, V_SLOT = 2, V_CB = 3, V_ENGINE = 4, V_NFIELDS = 5 };
enum { KIND_SOURCE = 1, KIND_SUBMIX = 2, KIND_MASTER = 3 };
enum { TAG_XA2 = 0x58410000, TAG_XA2V };
enum { MAX_VOICE = 64, QLEN = 64 };

/* One sub-block the mixer can play in one go: a buffer's play region, or one
 * pass of its loop region. */
typedef struct {
    const uint8_t *mem; uint32_t bytes;
    uint64_t ctx;
    int first, last;                 /* first/last sub-block of its XAUDIO2_BUFFER */
    int loop, loop_forever, eos;
} blk;
typedef struct {
    int      used, started;
    uint64_t obj;                    /* the voice object */
    int      src;                    /* mixer source id, or -1 until the first buffer */
    uint32_t freq, channels, bits; int is_float;
    float    volume, ratio, master;
    blk      q[QLEN]; int head, n;
    int      in_mixer;               /* how many of the front blocks the mixer holds (0..2) */
    uint64_t submitted, ended;       /* buffers, for BuffersQueued */
} voice;
static voice g_v[MAX_VOICE];
static float g_master = 1.0f;
static w32_com_class cls_xa7, cls_xa9, cls_src, cls_src7, cls_sub, cls_mas7, cls_mas9;
static w32_api xa7_m[XA7_NSLOTS], xa9_m[XA9_NSLOTS], src_m[XS_NSLOTS], src7_m[XS_NSLOTS], sub_m[XV_NSLOTS], mas7_m[XM7_NSLOTS], mas9_m[XM9_NSLOTS];
static int g_built;

static int32_t lin_to_mB(float v) {
    if (v <= 0.0f) return -10000;
    if (v >= 1.0f) return 0;
    double mB = 2000.0 * log10((double)v);
    return mB < -10000 ? -10000 : (int32_t)mB;
}
static uint32_t frame_bytes(const voice *v) { return (v->channels ? v->channels : 1) * ((v->bits ? v->bits : 16) / 8); }

/* --- callbacks into the game -------------------------------------------------- */
static void call_cb(w32 *w, uint64_t cb, int slot, int nargs, uint64_t a1, uint64_t a2) {
    if (!cb || w->exited) return;
    int psz = (int)w32_ptrsize(w);
    uint64_t vt = w32_read(w, cb, psz);
    if (!vt) return;
    uint64_t fn = w32_read(w, vt + (uint64_t)psz * (uint32_t)slot, psz);
    if (!fn) return;
    uint64_t args[3] = { cb, a1, a2 };
    w32_call_guest(w, fn, nargs, args);
}

/* --- the queue and the mixer ---------------------------------------------------- */
static void src_fill(const voice *v, const blk *b, w32_audio_src *s) {
    memset(s, 0, sizeof *s);
    s->mem = b->mem; s->size = b->bytes;
    s->freq = (uint32_t)((float)v->freq * (v->ratio > 0 ? v->ratio : 1.0f));
    s->channels = v->channels; s->bits = v->bits; s->is_float = v->is_float;
    s->playing = v->started; s->looping = b->loop_forever;
    s->vol_mB = lin_to_mB(v->volume * v->master * g_master);
}
/* Hand the mixer what it can take: the front block as current if it has
 * nothing, the second as its next. */
static void refill(w32 *w, voice *v) {
    (void)w;
    while (v->in_mixer < 2 && v->in_mixer < v->n) {
        blk *b = &v->q[(v->head + v->in_mixer) % QLEN];
        w32_audio_src s; src_fill(v, b, &s);
        if (v->src < 0) { v->src = w32_audio_src_add(&s); if (v->src < 0) return; }
        else if (v->in_mixer == 0) w32_audio_src_set(v->src, &s);
        else if (!w32_audio_src_queue_next(v->src, &s)) return;
        v->in_mixer++;
    }
    if (v->started && v->src >= 0) w32_audio_open();
}
static void voice_sync(voice *v) {
    if (v->src < 0 || v->in_mixer == 0) return;
    w32_audio_src s; src_fill(v, &v->q[v->head % QLEN], &s);
    w32_audio_src_set(v->src, &s);
}
/* What the mixer finished since last time: pop, tell the game, refill. */
static void voice_tick(w32 *w, voice *v) {
    if (v->src < 0) return;
    int ended = w32_audio_src_take_ended(v->src);
    uint64_t cb = w32_com_get(w, v->obj, V_CB);
    while (ended-- > 0 && v->n > 0) {
        blk done = v->q[v->head % QLEN];
        v->head++; v->n--; if (v->in_mixer > 0) v->in_mixer--;
        if (done.loop && !done.last) call_cb(w, cb, CB_OnLoopEnd, 2, done.ctx, 0);
        if (done.last) { v->ended++; call_cb(w, cb, CB_OnBufferEnd, 2, done.ctx, 0); }
        if (v->n > 0 && v->q[v->head % QLEN].first) call_cb(w, cb, CB_OnBufferStart, 2, v->q[v->head % QLEN].ctx, 0);
        if (done.last && done.eos && v->n == 0) call_cb(w, cb, CB_OnStreamEnd, 1, 0, 0);
        if (w->exited) return;
    }
    refill(w, v);
}
static int g_in_tick;
void w32_xaudio2_tick(w32 *w) {
    if (!g_built || g_in_tick) return;
    g_in_tick = 1;
    w32_audio_pump();
    for (int i = 0; i < MAX_VOICE && !w->exited; i++) if (g_v[i].used) voice_tick(w, &g_v[i]);
    g_in_tick = 0;
}

/* --- the voice --------------------------------------------------------------- */
static voice *voice_of(w32 *w, uint64_t obj) {
    int i = (int)w32_com_get(w, obj, V_SLOT) - 1;
    return i >= 0 && i < MAX_VOICE && g_v[i].used ? &g_v[i] : 0;
}
static void v_GetVoiceDetails(w32 *w) {
    uint64_t p = ARG(1); int ver = (int)w32_com_get(w, ARG(0), V_VER);
    voice *v = voice_of(w, ARG(0));
    if (!p || !w32_mem_ok(w, p, ver >= 8 ? 16 : 12)) { RET((uint64_t)(uint32_t)E_INVALIDARG_); return; }
    uint64_t at = p;
    w32_write(w, at, 4, 0); at += 4;                                  /* CreationFlags */
    if (ver >= 8) { w32_write(w, at, 4, 0); at += 4; }                /* ActiveFlags */
    w32_write(w, at, 4, v ? v->channels : 2); w32_write(w, at + 4, 4, v ? v->freq : 44100);
    RET(S_OK_);
}
static void v_ok(w32 *w) { (void)w; RET(S_OK_); }
static void v_unsupported(w32 *w) { (void)w; RET((uint64_t)(uint32_t)E_NOTIMPL_); }
static void v_SetVolume(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    float f = w32_fargf(w, 1);
    if (f < 0) f = 0;
    if (v) {
        if (v->src < 0 && (int)w32_com_get(w, ARG(0), V_KIND) == KIND_MASTER) g_master = f;
        v->volume = f; voice_sync(v);
        if ((int)w32_com_get(w, ARG(0), V_KIND) == KIND_MASTER) {   /* every source hears the master */
            g_master = f;
            for (int i = 0; i < MAX_VOICE; i++) if (g_v[i].used) voice_sync(&g_v[i]);
        }
    }
    RET(S_OK_);
}
static void v_GetVolume(w32 *w) {
    voice *v = voice_of(w, ARG(0)); float f = v ? v->volume : 1.0f; uint32_t bits; memcpy(&bits, &f, 4);
    if (ARG(1)) w32_write(w, ARG(1), 4, bits);
    RET(0);
}
static void v_GetChannelVolumes(w32 *w) {
    voice *v = voice_of(w, ARG(0)); float f = v ? v->volume : 1.0f; uint32_t bits; memcpy(&bits, &f, 4);
    uint32_t n = (uint32_t)ARG(1);
    if (ARG(2) && n <= 8 && w32_mem_ok(w, ARG(2), 4ull * n)) for (uint32_t i = 0; i < n; i++) w32_write(w, ARG(2) + 4ull * i, 4, bits);
    RET(0);
}
static void v_GetOutputMatrix(w32 *w) {
    uint32_t sc = (uint32_t)ARG(2), dc = (uint32_t)ARG(3); float one = 1.0f; uint32_t bits; memcpy(&bits, &one, 4);
    if (ARG(4) && sc * dc <= 64 && w32_mem_ok(w, ARG(4), 4ull * sc * dc))
        for (uint32_t i = 0; i < sc * dc; i++) w32_write(w, ARG(4) + 4ull * i, 4, (i % (sc + 1)) == 0 ? bits : 0);
    RET(0);
}
static void v_DestroyVoice(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    if (v) { if (v->src >= 0) w32_audio_src_remove(v->src); memset(v, 0, sizeof *v); }
    w32_com_set(w, ARG(0), V_SLOT, 0);
    RET(0);
}
static void v_GetEffectState(w32 *w) { if (ARG(2)) w32_write(w, ARG(2), 4, 0); RET(0); }
static void v_GetFilterParameters(w32 *w) {
    /* XAUDIO2_FILTER_PARAMETERS { Type; Frequency; OneOverQ }: a low-pass at the top, Q 1 -- the default */
    float freq = 1.0f, q = 1.0f; uint32_t fb, qb; memcpy(&fb, &freq, 4); memcpy(&qb, &q, 4);
    uint64_t p = ARG(1);
    if (p && w32_mem_ok(w, p, 12)) { w32_write(w, p, 4, 0); w32_write(w, p + 4, 4, fb); w32_write(w, p + 8, 4, qb); }
    RET(0);
}
static void v_GetOutputFilterParameters(w32 *w) {
    float freq = 1.0f, q = 1.0f; uint32_t fb, qb; memcpy(&fb, &freq, 4); memcpy(&qb, &q, 4);
    uint64_t p = ARG(2);
    if (p && w32_mem_ok(w, p, 12)) { w32_write(w, p, 4, 0); w32_write(w, p + 4, 4, fb); w32_write(w, p + 8, 4, qb); }
    RET(0);
}

/* source voice */
static void s_Start(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    if (!v) { RET((uint64_t)(uint32_t)XAUDIO2_E_INVALID_CALL_); return; }
    int was = v->started;
    v->started = 1; voice_sync(v); refill(w, v);
    if (v->src >= 0) w32_audio_open();
    if (!was && v->n > 0 && v->q[v->head % QLEN].first) call_cb(w, w32_com_get(w, ARG(0), V_CB), CB_OnBufferStart, 2, v->q[v->head % QLEN].ctx, 0);
    RET(S_OK_);
}
static void s_Stop(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    if (v) { v->started = 0; voice_sync(v); }
    RET(S_OK_);
}
/* XAUDIO2_BUFFER: Flags, AudioBytes, pAudioData, PlayBegin, PlayLength, LoopBegin,
 * LoopLength, LoopCount, pContext -- the pointers pad it differently per bitness. */
static void s_SubmitSourceBuffer(w32 *w) {
    voice *v = voice_of(w, ARG(0)); uint64_t b = ARG(1); int psz = (int)w32_ptrsize(w);
    if (!v) { RET((uint64_t)(uint32_t)XAUDIO2_E_INVALID_CALL_); return; }
    if (!b || !w32_mem_ok(w, b, psz == 4 ? 36 : 48)) { RET((uint64_t)(uint32_t)E_INVALIDARG_); return; }
    uint32_t flags = (uint32_t)w32_read(w, b, 4), bytes = (uint32_t)w32_read(w, b + 4, 4);
    uint64_t data = w32_read(w, b + 8, psz), o = psz == 4 ? 12 : 16;
    uint32_t begin = (uint32_t)w32_read(w, b + o, 4), len = (uint32_t)w32_read(w, b + o + 4, 4);
    uint32_t lbegin = (uint32_t)w32_read(w, b + o + 8, 4), llen = (uint32_t)w32_read(w, b + o + 12, 4), lcount = (uint32_t)w32_read(w, b + o + 16, 4);
    uint64_t ctx = w32_read(w, b + (psz == 4 ? 32 : 40), psz);
    uint32_t fb = frame_bytes(v), total = fb ? bytes / fb : 0;
    const uint8_t *mem = W32PN(w, data, bytes);
    if (!mem || !total) { RET((uint64_t)(uint32_t)XAUDIO2_E_INVALID_CALL_); return; }
    if (begin >= total) begin = 0;
    if (!len || begin + len > total) len = total - begin;
    /* the play region once, then the loop region as many times as asked */
    int nblk = 1 + (lcount ? (lcount == XAUDIO2_LOOP_INFINITE_ ? 1 : (int)(lcount > 8 ? 8 : lcount)) : 0);
    if (v->n + nblk > QLEN) { RET((uint64_t)(uint32_t)XAUDIO2_E_INVALID_CALL_); return; }
    blk *first = &v->q[(v->head + v->n) % QLEN];
    memset(first, 0, sizeof *first);
    first->mem = mem + (uint64_t)begin * fb; first->bytes = len * fb; first->ctx = ctx; first->first = 1;
    first->last = nblk == 1; first->eos = (flags & XAUDIO2_END_OF_STREAM_) != 0;
    v->n++;
    if (lcount) {
        if (lbegin >= total) lbegin = begin;
        if (!llen || lbegin + llen > total) llen = total - lbegin;
        for (int k = 1; k < nblk; k++) {
            blk *l = &v->q[(v->head + v->n) % QLEN];
            memset(l, 0, sizeof *l);
            l->mem = mem + (uint64_t)lbegin * fb; l->bytes = llen * fb; l->ctx = ctx; l->loop = 1;
            l->loop_forever = lcount == XAUDIO2_LOOP_INFINITE_;
            l->last = k == nblk - 1; l->eos = first->eos;
            v->n++;
        }
    }
    v->submitted++;
    int was_empty = v->in_mixer == 0;
    refill(w, v);
    if (was_empty && v->started) call_cb(w, w32_com_get(w, ARG(0), V_CB), CB_OnBufferStart, 2, ctx, 0);
    RET(S_OK_);
}
static void s_FlushSourceBuffers(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    if (!v) { RET((uint64_t)(uint32_t)XAUDIO2_E_INVALID_CALL_); return; }
    uint64_t cb = w32_com_get(w, ARG(0), V_CB);
    /* everything behind the block playing goes, and each buffer it belonged to
     * is reported ended; a stopped voice has nothing playing, so it loses the
     * head as well */
    int keep = v->started && v->in_mixer > 0 ? 1 : 0;
    if (v->src >= 0 && v->in_mixer > 1) w32_audio_src_clear_next(v->src);
    if (v->src >= 0 && !keep && v->in_mixer > 0) { w32_audio_src s; src_fill(v, &v->q[v->head % QLEN], &s); s.playing = 0; s.mem = 0; s.size = 0; w32_audio_src_set(v->src, &s); }
    while (v->n > keep) {
        blk gone = v->q[(v->head + v->n - 1) % QLEN];
        v->n--;
        if (gone.last) { v->ended++; call_cb(w, cb, CB_OnBufferEnd, 2, gone.ctx, 0); }
    }
    v->in_mixer = keep;
    RET(S_OK_);
}
static void s_ExitLoop(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    if (v && v->n > 0) {
        blk *cur = &v->q[v->head % QLEN];
        if (cur->loop_forever) { cur->loop_forever = 0; cur->last = 1; voice_sync(v); }
        /* drop the remaining loop passes of the current buffer */
        int keep = 1;
        while (v->n > keep && v->q[(v->head + keep) % QLEN].loop && !v->q[(v->head + keep) % QLEN].first) {
            v->q[(v->head + keep) % QLEN] = v->q[(v->head + v->n - 1) % QLEN]; v->n--;   /* not order-preserving past the loop; nothing follows a loop pass but its own siblings */
        }
        v->q[v->head % QLEN].last = 1;
        if (v->in_mixer > 1) { w32_audio_src_clear_next(v->src); v->in_mixer = 1; }
    }
    RET(S_OK_);
}
/* XAUDIO2_VOICE_STATE { pCurrentBufferContext; BuffersQueued; SamplesPlayed } */
static void s_GetState(w32 *w) {
    voice *v = voice_of(w, ARG(0)); uint64_t p = ARG(1); int psz = (int)w32_ptrsize(w);
    w32_xaudio2_tick(w);
    if (!p || !w32_mem_ok(w, p, psz == 4 ? 16 : 24)) { RET(0); return; }
    uint64_t ctx = 0; uint32_t queued = 0; uint64_t played = 0;
    if (v) {
        for (int i = 0; i < v->n; i++) if (v->q[(v->head + i) % QLEN].first) queued++;
        if (v->n > 0) { ctx = v->q[v->head % QLEN].ctx; if (!v->q[v->head % QLEN].first) queued++; }
        if (v->src >= 0) played = w32_audio_src_frames_done(v->src);
    }
    w32_write(w, p, psz, ctx);
    w32_write(w, p + psz, 4, queued);
    w32_write(w, p + (psz == 4 ? 8 : 16), 8, played);
    RET(0);
}
static void s_SetFrequencyRatio(w32 *w) {
    voice *v = voice_of(w, ARG(0)); float r = w32_fargf(w, 1);
    if (r < 1.0f / 1024) r = 1.0f / 1024; if (r > 1024.0f) r = 1024.0f;
    if (v) { v->ratio = r; voice_sync(v); }
    RET(S_OK_);
}
static void s_GetFrequencyRatio(w32 *w) {
    voice *v = voice_of(w, ARG(0)); float r = v ? v->ratio : 1.0f; uint32_t bits; memcpy(&bits, &r, 4);
    if (ARG(1)) w32_write(w, ARG(1), 4, bits);
    RET(0);
}
static void s_SetSourceSampleRate(w32 *w) {
    voice *v = voice_of(w, ARG(0));
    if (v && ARG(1)) { v->freq = (uint32_t)ARG(1); voice_sync(v); }
    RET(S_OK_);
}
static void m_GetChannelMask(w32 *w) { if (ARG(1)) w32_write(w, ARG(1), 4, 3); RET(S_OK_); }   /* SPEAKER_FRONT_LEFT | RIGHT */

/* --- the engine ----------------------------------------------------------------- */
static uint64_t make_voice(w32 *w, int kind, int ver, uint64_t engine) {
    int slot = -1;
    for (int i = 0; i < MAX_VOICE; i++) if (!g_v[i].used) { slot = i; break; }
    if (slot < 0) return 0;
    w32_com_class *cls = kind == KIND_SOURCE ? (ver >= 8 ? &cls_src : &cls_src7) : kind == KIND_SUBMIX ? &cls_sub : ver >= 8 ? &cls_mas9 : &cls_mas7;
    uint64_t o = w32_com_new(w, cls, V_NFIELDS);
    if (!o) return 0;
    voice *v = &g_v[slot];
    memset(v, 0, sizeof *v);
    v->used = 1; v->obj = o; v->src = -1; v->volume = 1.0f; v->ratio = 1.0f; v->master = 1.0f;
    v->freq = 44100; v->channels = 2; v->bits = 16;
    w32_com_set(w, o, V_KIND, (uint64_t)kind); w32_com_set(w, o, V_VER, (uint64_t)ver);
    w32_com_set(w, o, V_SLOT, (uint64_t)slot + 1); w32_com_set(w, o, V_ENGINE, engine);
    return o;
}
/* CreateSourceVoice(ppVoice, pFormat, Flags, MaxFrequencyRatio, pCallback, pSendList, pEffectChain) */
static void e_CreateSourceVoice(w32 *w) {
    uint64_t out = ARG(1), fmt = ARG(2), cb = ARG(4); int ver = (int)w32_com_get(w, ARG(0), E_VER);
    if (!out) { RET((uint64_t)(uint32_t)E_POINTER_); return; }
    if (!fmt || !w32_mem_ok(w, fmt, 16)) { RET((uint64_t)(uint32_t)E_INVALIDARG_); return; }
    uint32_t tag = (uint32_t)w32_read(w, fmt, 2), ch = (uint32_t)w32_read(w, fmt + 2, 2), rate = (uint32_t)w32_read(w, fmt + 4, 4), bits = (uint32_t)w32_read(w, fmt + 14, 2);
    if (tag == 0xFFFE && w32_mem_ok(w, fmt, 40)) tag = (uint32_t)w32_read(w, fmt + 24, 2);
    if ((tag != 1 && tag != 3) || !ch || !rate || !bits) {
        static char note[96]; snprintf(note, sizeof note, "xaudio2!CreateSourceVoice (format tag %u: only PCM and float are decoded here)", tag);
        w32_note_refused(w, note);
        w32_write(w, out, (int)w32_ptrsize(w), 0);
        RET((uint64_t)(uint32_t)XAUDIO2_E_INVALID_CALL_); return;
    }
    uint64_t o = make_voice(w, KIND_SOURCE, ver, ARG(0));
    if (!o) { RET((uint64_t)(uint32_t)E_FAIL_); return; }
    voice *v = voice_of(w, o);
    v->freq = rate; v->channels = ch; v->bits = bits; v->is_float = tag == 3; v->master = g_master;
    w32_com_set(w, o, V_CB, cb);
    w32_write(w, out, (int)w32_ptrsize(w), o);
    if (w->verbose) fprintf(stderr, "winrun: xaudio2: source voice %u Hz, %u ch, %u bit%s%s\n", rate, ch, bits, v->is_float ? " float" : "", cb ? ", with callback" : "");
    RET(S_OK_);
}
static void e_CreateSubmixVoice(w32 *w) {
    uint64_t out = ARG(1); int ver = (int)w32_com_get(w, ARG(0), E_VER);
    if (!out) { RET((uint64_t)(uint32_t)E_POINTER_); return; }
    uint64_t o = make_voice(w, KIND_SUBMIX, ver, ARG(0));
    if (!o) { RET((uint64_t)(uint32_t)E_FAIL_); return; }
    w32_write(w, out, (int)w32_ptrsize(w), o);
    RET(S_OK_);
}
static void e_CreateMasteringVoice(w32 *w) {
    uint64_t out = ARG(1); int ver = (int)w32_com_get(w, ARG(0), E_VER);
    if (!out) { RET((uint64_t)(uint32_t)E_POINTER_); return; }
    uint64_t o = make_voice(w, KIND_MASTER, ver, ARG(0));
    if (!o) { RET((uint64_t)(uint32_t)E_FAIL_); return; }
    w32_write(w, out, (int)w32_ptrsize(w), o);
    w32_audio_open();
    if (w->verbose) fprintf(stderr, "winrun: xaudio2 %d: mastering voice, %s\n", ver, w32_audio_device_on() ? "device open" : "no device");
    RET(S_OK_);
}
static void e_StartEngine(w32 *w) {
    w32_com_set(w, ARG(0), E_RUNNING, 1);
    for (int i = 0; i < MAX_VOICE; i++) if (g_v[i].used) voice_sync(&g_v[i]);
    RET(S_OK_);
}
static void e_StopEngine(w32 *w) {
    w32_com_set(w, ARG(0), E_RUNNING, 0);
    for (int i = 0; i < MAX_VOICE; i++) if (g_v[i].used && g_v[i].src >= 0 && g_v[i].in_mixer) {
        w32_audio_src s; src_fill(&g_v[i], &g_v[i].q[g_v[i].head % QLEN], &s); s.playing = 0; w32_audio_src_set(g_v[i].src, &s);
    }
    RET(0);
}
static void e_GetPerformanceData(w32 *w) { if (ARG(1) && w32_mem_ok(w, ARG(1), 64)) for (int i = 0; i < 64; i += 4) w32_write(w, ARG(1) + i, 4, 0); RET(0); }
static void e_ok(w32 *w) { (void)w; RET(S_OK_); }
static void e_void(w32 *w) { (void)w; RET(0); }
/* 2.7: GetDeviceCount / GetDeviceDetails / Initialize */
static void e7_GetDeviceCount(w32 *w) { if (ARG(1)) w32_write(w, ARG(1), 4, 1); RET(S_OK_); }
static void e7_GetDeviceDetails(w32 *w) {
    /* XAUDIO2_DEVICE_DETAILS { WCHAR DeviceID[256]; WCHAR DisplayName[256]; Role; WAVEFORMATEXTENSIBLE OutputFormat } */
    uint64_t p = ARG(2);
    if ((uint32_t)ARG(1) != 0) { RET((uint64_t)(uint32_t)E_INVALIDARG_); return; }
    if (!p || !w32_mem_ok(w, p, 512 + 512 + 4 + 40)) { RET((uint64_t)(uint32_t)E_INVALIDARG_); return; }
    static const char *id = "winios-audio", *name = "Winios Audio";
    for (int i = 0; i < 256; i++) { w32_write(w, p + 2 * i, 2, i < (int)strlen(id) ? (uint8_t)id[i] : 0); w32_write(w, p + 512 + 2 * i, 2, i < (int)strlen(name) ? (uint8_t)name[i] : 0); }
    w32_write(w, p + 1024, 4, 0xF);                                   /* GlobalDefaultDevice */
    uint64_t f = p + 1028;
    w32_write(w, f, 2, 1); w32_write(w, f + 2, 2, 2); w32_write(w, f + 4, 4, 44100); w32_write(w, f + 8, 4, 44100 * 4);
    w32_write(w, f + 12, 2, 4); w32_write(w, f + 14, 2, 16); w32_write(w, f + 16, 2, 0);
    for (int i = 18; i < 40; i++) w32_write(w, f + i, 1, 0);
    RET(S_OK_);
}

#define M(tab, slot, nm, na, f) do { (tab)[slot].name = (nm); (tab)[slot].nargs = (na); (tab)[slot].fn = (f); } while (0)
static void voice_common(w32_api *d, int has_state_flags) {
    (void)has_state_flags;
    M(d, XV_GetVoiceDetails, "GetVoiceDetails", 2, v_GetVoiceDetails);
    M(d, XV_SetOutputVoices, "SetOutputVoices", 2, v_ok);
    M(d, XV_SetEffectChain, "SetEffectChain", 2, v_ok);
    M(d, XV_EnableEffect, "EnableEffect", 3, v_ok);
    M(d, XV_DisableEffect, "DisableEffect", 3, v_ok);
    M(d, XV_GetEffectState, "GetEffectState", 3, v_GetEffectState);
    M(d, XV_SetEffectParameters, "SetEffectParameters", 5, v_ok);
    M(d, XV_GetEffectParameters, "GetEffectParameters", 4, v_unsupported);
    M(d, XV_SetFilterParameters, "SetFilterParameters", 3, v_ok);
    M(d, XV_GetFilterParameters, "GetFilterParameters", 2, v_GetFilterParameters);
    M(d, XV_SetOutputFilterParameters, "SetOutputFilterParameters", 4, v_ok);
    M(d, XV_GetOutputFilterParameters, "GetOutputFilterParameters", 3, v_GetOutputFilterParameters);
    M(d, XV_SetVolume, "SetVolume", 3, v_SetVolume);
    M(d, XV_GetVolume, "GetVolume", 2, v_GetVolume);
    M(d, XV_SetChannelVolumes, "SetChannelVolumes", 4, v_ok);
    M(d, XV_GetChannelVolumes, "GetChannelVolumes", 3, v_GetChannelVolumes);
    M(d, XV_SetOutputMatrix, "SetOutputMatrix", 6, v_ok);
    M(d, XV_GetOutputMatrix, "GetOutputMatrix", 5, v_GetOutputMatrix);
    M(d, XV_DestroyVoice, "DestroyVoice", 1, v_DestroyVoice);
}
static void build_tables(void) {
    if (g_built) return;
    g_built = 1;
    for (int i = 0; i < XA7_NSLOTS; i++) xa7_m[i] = (w32_api){ 0, 0, 0, 0, 0 };
    for (int i = 0; i < XA9_NSLOTS; i++) xa9_m[i] = (w32_api){ 0, 0, 0, 0, 0 };
    for (int i = 0; i < XS_NSLOTS; i++)  src_m[i]  = (w32_api){ 0, 0, 0, 0, 0 };
    for (int i = 0; i < XV_NSLOTS; i++)  sub_m[i]  = (w32_api){ 0, 0, 0, 0, 0 };
    for (int i = 0; i < XM7_NSLOTS; i++) mas7_m[i] = (w32_api){ 0, 0, 0, 0, 0 };
    for (int i = 0; i < XM9_NSLOTS; i++) mas9_m[i] = (w32_api){ 0, 0, 0, 0, 0 };
    w32_api *e[2] = { xa7_m, xa9_m };
    for (int t = 0; t < 2; t++) {
        int o = t == 0 ? 3 : 0;                    /* 2.7's three extra slots */
        M(e[t], XA_QueryInterface, "QueryInterface", 3, w32_com_QueryInterface);
        M(e[t], XA_AddRef, "AddRef", 1, w32_com_AddRef);
        M(e[t], XA_Release, "Release", 1, w32_com_Release);
        M(e[t], XA9_RegisterForCallbacks + o, "RegisterForCallbacks", 2, e_ok);
        M(e[t], XA9_UnregisterForCallbacks + o, "UnregisterForCallbacks", 2, e_void);
        M(e[t], XA9_CreateSourceVoice + o, "CreateSourceVoice", 8, e_CreateSourceVoice);
        M(e[t], XA9_CreateSubmixVoice + o, "CreateSubmixVoice", 8, e_CreateSubmixVoice);
        M(e[t], XA9_CreateMasteringVoice + o, "CreateMasteringVoice", t == 0 ? 7 : 8, e_CreateMasteringVoice);
        M(e[t], XA9_StartEngine + o, "StartEngine", 1, e_StartEngine);
        M(e[t], XA9_StopEngine + o, "StopEngine", 1, e_StopEngine);
        M(e[t], XA9_CommitChanges + o, "CommitChanges", 2, e_ok);
        M(e[t], XA9_GetPerformanceData + o, "GetPerformanceData", 2, e_GetPerformanceData);
        M(e[t], XA9_SetDebugConfiguration + o, "SetDebugConfiguration", 3, e_void);
    }
    M(xa7_m, XA7_GetDeviceCount, "GetDeviceCount", 2, e7_GetDeviceCount);
    M(xa7_m, XA7_GetDeviceDetails, "GetDeviceDetails", 3, e7_GetDeviceDetails);
    M(xa7_m, XA7_Initialize, "Initialize", 3, e_ok);
    voice_common(src_m, 1); voice_common(sub_m, 0); voice_common(mas7_m, 0); voice_common(mas9_m, 0);
    M(src_m, XS_Start, "Start", 3, s_Start);
    M(src_m, XS_Stop, "Stop", 3, s_Stop);
    M(src_m, XS_SubmitSourceBuffer, "SubmitSourceBuffer", 3, s_SubmitSourceBuffer);
    M(src_m, XS_FlushSourceBuffers, "FlushSourceBuffers", 1, s_FlushSourceBuffers);
    M(src_m, XS_Discontinuity, "Discontinuity", 1, v_ok);
    M(src_m, XS_ExitLoop, "ExitLoop", 2, s_ExitLoop);
    M(src_m, XS_GetState, "GetState", 3, s_GetState);          /* 2.7's GetState has two arguments; see cls_src7 below */
    M(src_m, XS_SetFrequencyRatio, "SetFrequencyRatio", 3, s_SetFrequencyRatio);
    M(src_m, XS_GetFrequencyRatio, "GetFrequencyRatio", 2, s_GetFrequencyRatio);
    M(src_m, XS_SetSourceSampleRate, "SetSourceSampleRate", 2, s_SetSourceSampleRate);
    M(mas9_m, XM9_GetChannelMask, "GetChannelMask", 2, m_GetChannelMask);
    /* A 2.7 source voice differs in one slot's argument count -- GetState has
     * no Flags -- which on x86 is the number of bytes to pop. Its own table. */
    memcpy(src7_m, src_m, sizeof src7_m);
    M(src7_m, XS_GetState, "GetState", 2, s_GetState);
    cls_src7 = (w32_com_class){ "IXAudio2SourceVoice (2.7)", src7_m, XS_NSLOTS, TAG_XA2V, 0, {0} };
    cls_xa7  = (w32_com_class){ "IXAudio2 (2.7)",          xa7_m,  XA7_NSLOTS, TAG_XA2,  0, {0} };
    cls_xa9  = (w32_com_class){ "IXAudio2",                xa9_m,  XA9_NSLOTS, TAG_XA2,  0, {0} };
    cls_src  = (w32_com_class){ "IXAudio2SourceVoice",     src_m,  XS_NSLOTS,  TAG_XA2V, 0, {0} };
    cls_sub  = (w32_com_class){ "IXAudio2SubmixVoice",     sub_m,  XV_NSLOTS,  TAG_XA2V, 0, {0} };
    cls_mas7 = (w32_com_class){ "IXAudio2MasteringVoice (2.7)", mas7_m, XM7_NSLOTS, TAG_XA2V, 0, {0} };
    cls_mas9 = (w32_com_class){ "IXAudio2MasteringVoice",  mas9_m, XM9_NSLOTS, TAG_XA2V, 0, {0} };
}
static uint64_t make_engine(w32 *w, int ver) {
    build_tables();
    uint64_t o = w32_com_new(w, ver >= 8 ? &cls_xa9 : &cls_xa7, E_NFIELDS);
    if (o) { w32_com_set(w, o, E_VER, (uint64_t)ver); w32_com_set(w, o, E_RUNNING, 1); }
    return o;
}

/* XAudio2Create(ppXAudio2, Flags, XAudio2Processor): xaudio2_8 and _9 */
static void x_XAudio2Create(w32 *w) {
    uint64_t out = ARG(0);
    if (!out) { RET((uint64_t)(uint32_t)E_POINTER_); return; }
    uint64_t o = make_engine(w, 9);
    if (!o) { RET((uint64_t)(uint32_t)E_FAIL_); return; }
    w32_write(w, out, (int)w32_ptrsize(w), o);
    if (w->verbose) fprintf(stderr, "winrun: xaudio2: engine created (2.8/2.9 layout)\n");
    RET(S_OK_);
}
static void x_CreateAudioVolumeMeter(w32 *w) { if (ARG(0)) w32_write(w, ARG(0), (int)w32_ptrsize(w), 0); RET((uint64_t)(uint32_t)E_NOTIMPL_); }
static void x_CreateAudioReverb(w32 *w) { if (ARG(0)) w32_write(w, ARG(0), (int)w32_ptrsize(w), 0); RET((uint64_t)(uint32_t)E_NOTIMPL_); }
static void x_CreateFX(w32 *w) { if (ARG(1)) w32_write(w, ARG(1), (int)w32_ptrsize(w), 0); RET((uint64_t)(uint32_t)E_NOTIMPL_); }
static void x_DllGetClassObject(w32 *w) { (void)w; RET(0x80040111u); }
static void x_DllCanUnloadNow(w32 *w) { (void)w; RET(1); }

/* The 2.0..2.7 CLSIDs, release and debug, from xaudio2.idl. */
static const uint8_t CLSIDS_27[][16] = {
    W32_GUID(0xfac23f48, 0x31f5, 0x45a8, 0xb4,0x9b,0x52,0x25,0xd6,0x14,0x01,0xaa), W32_GUID(0xe21a7345, 0xeb21, 0x468e, 0xbe,0x50,0x80,0x4d,0xb9,0x7c,0xf7,0x08),
    W32_GUID(0xb802058a, 0x464a, 0x42db, 0xbc,0x10,0xb6,0x50,0xd6,0xf2,0x58,0x6a), W32_GUID(0x4c5e637a, 0x16c7, 0x4de3, 0x9c,0x46,0x5e,0xd2,0x21,0x81,0x96,0x2d),
    W32_GUID(0x03219e78, 0x5bc3, 0x44d1, 0xb9,0x2e,0xf6,0x3d,0x89,0xcc,0x65,0x26), W32_GUID(0x4c9b6dde, 0x6809, 0x46e6, 0xa2,0x78,0x9b,0x6a,0x97,0x58,0x86,0x70),
    W32_GUID(0x3eda9b49, 0x2085, 0x498b, 0x9b,0xb2,0x39,0xa6,0x77,0x84,0x93,0xde), W32_GUID(0x5a508685, 0xa254, 0x4fba, 0x9b,0x82,0x9a,0x24,0xb0,0x03,0x06,0xaf),
    W32_GUID(0xfac23f48, 0x31f5, 0x45a8, 0xb4,0x9b,0x52,0x25,0xd6,0x14,0x01,0xdb), W32_GUID(0xf7a76c21, 0x53d4, 0x46bb, 0xac,0x53,0x8b,0x45,0x9c,0xae,0x46,0xbd),
    W32_GUID(0x97dfb7e7, 0x5161, 0x4015, 0x87,0xa9,0xc7,0x9e,0x6a,0x19,0x52,0xcc), W32_GUID(0xef0aa05d, 0x8075, 0x4e5d, 0xbe,0xad,0x45,0xbe,0x0c,0x3c,0xcb,0xb3),
    W32_GUID(0x4256535c, 0x1ea4, 0x4d4b, 0x8a,0xd5,0xf9,0xdb,0x76,0x2e,0xca,0x9e), W32_GUID(0x715bdd1a, 0xaa82, 0x436b, 0xb0,0xfa,0x6a,0xce,0xa3,0x9b,0xd0,0xa1),
    W32_GUID(0x47199894, 0x7cc2, 0x444d, 0x98,0x73,0xce,0xd2,0x56,0x2c,0xc6,0x0e), W32_GUID(0xdb05ea35, 0x0329, 0x4d4b, 0xa5,0x3a,0x6d,0xea,0xd0,0x3d,0x38,0x52),
};
int w32_xaudio2_create_class(w32 *w, const uint8_t clsid[16], const uint8_t iid[16], uint64_t out) {
    (void)iid;
    int hit = 0;
    for (size_t i = 0; i < sizeof CLSIDS_27 / sizeof CLSIDS_27[0]; i++) if (!memcmp(clsid, CLSIDS_27[i], 16)) hit = 1;
    if (!hit) return 0;
    uint64_t o = make_engine(w, 7);
    if (!o) return 0;
    w32_write(w, out, (int)w32_ptrsize(w), o);
    if (w->verbose) fprintf(stderr, "winrun: xaudio2: engine created through CoCreateInstance (2.7 layout)\n");
    return 1;
}

void w32_xaudio2_reset(void) { g_built = 0; memset(g_v, 0, sizeof g_v); g_master = 1.0f; }

#define F(n, a)  { #n, a, 0, x_##n, 0 }
const w32_api w32_xaudio2[] = {
    F(XAudio2Create, 3), F(CreateAudioVolumeMeter, 1), F(CreateAudioReverb, 1), F(CreateFX, 4),
    F(DllGetClassObject, 3), F(DllCanUnloadNow, 0),
    { 0, 0, 0, 0, 0 },
};
