/* census: which x86-64 instructions does a binary actually use?
 *
 * Decodes every executable section of an ELF64 file with Zydis and prints a
 * histogram of mnemonics, marking the ones xcore's interpreter does not yet
 * implement. This is how the interpreter's growth is ordered: by what real
 * programs execute, not by the alphabet.
 *
 *   census <elf> [interp.c]
 */
#include <Zydis/Zydis.h>
#include <elf.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char *name; uint64_t count; int implemented; } row;

static char *slurp(const char *path, size_t *n) {
    FILE *f = fopen(path, "rb"); if (!f) return NULL;
    fseek(f, 0, SEEK_END); long len = ftell(f); fseek(f, 0, SEEK_SET);
    char *b = malloc((size_t)len + 1); fread(b, 1, (size_t)len, f); b[len] = 0; fclose(f);
    *n = (size_t)len; return b;
}

static int cmp_count(const void *a, const void *b) {
    const row *x = a, *y = b;
    return x->count < y->count ? 1 : x->count > y->count ? -1 : 0;
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: census <elf64> [interp.c]\n"); return 2; }
    size_t n; char *img = slurp(argv[1], &n);
    if (!img || n < sizeof(Elf64_Ehdr) || memcmp(img, ELFMAG, SELFMAG)) { fprintf(stderr, "not an ELF\n"); return 1; }
    const Elf64_Ehdr *eh = (const Elf64_Ehdr *)img;
    const Elf64_Shdr *sh = (const Elf64_Shdr *)(img + eh->e_shoff);

    size_t srcn = 0; char *src = argc > 2 ? slurp(argv[2], &srcn) : NULL;

    static uint64_t counts[ZYDIS_MNEMONIC_MAX_VALUE + 1];
    uint64_t total = 0;
    ZydisDecoder d; ZydisDecoderInit(&d, ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_STACK_WIDTH_64);
    for (int i = 0; i < eh->e_shnum; i++) {
        if (!(sh[i].sh_flags & SHF_EXECINSTR) || sh[i].sh_type != SHT_PROGBITS) continue;
        const uint8_t *p = (const uint8_t *)img + sh[i].sh_offset;
        size_t off = 0, len = sh[i].sh_size;
        while (off < len) {
            ZydisDecodedInstruction in;
            if (!ZYAN_SUCCESS(ZydisDecoderDecodeInstruction(&d, NULL, p + off, len - off, &in))) { off++; continue; }
            counts[in.mnemonic]++; total++;
            off += in.length;
        }
    }

    row rows[ZYDIS_MNEMONIC_MAX_VALUE + 1]; int nrows = 0;
    uint64_t covered = 0; int missing = 0;
    for (int m = 0; m <= ZYDIS_MNEMONIC_MAX_VALUE; m++) {
        if (!counts[m]) continue;
        const char *name = ZydisMnemonicGetString((ZydisMnemonic)m);
        int impl = 1;
        if (src) {
            char tok[96]; snprintf(tok, sizeof tok, "ZYDIS_MNEMONIC_%s", name);
            for (char *q = tok; *q; q++) if (*q >= 'a' && *q <= 'z') *q -= 32;
            /* whole-token match: the next char must not continue the identifier */
            impl = 0;
            for (const char *s = src; (s = strstr(s, tok)); s += strlen(tok)) {
                char c = s[strlen(tok)];
                if (!(c == '_' || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9'))) { impl = 1; break; }
            }
            /* jcc/setcc/cmovcc are generated by a macro family */
            if (!impl && (!strncmp(name, "j", 1) || !strncmp(name, "set", 3) || !strncmp(name, "cmov", 4))) impl = 1;
        }
        rows[nrows++] = (row){ name, counts[m], impl };
        if (impl) covered += counts[m]; else missing++;
    }
    qsort(rows, (size_t)nrows, sizeof(row), cmp_count);

    printf("%s: %llu instructions, %d distinct mnemonics", argv[1], (unsigned long long)total, nrows);
    if (src) printf(", %.2f%% of instructions covered by the interpreter, %d mnemonics missing", 100.0 * (double)covered / (double)total, missing);
    printf("\n");
    for (int i = 0; i < nrows; i++)
        printf("  %-16s %10llu  %6.2f%%  %s\n", rows[i].name, (unsigned long long)rows[i].count,
               100.0 * (double)rows[i].count / (double)total, rows[i].implemented ? "" : "MISSING");
    return 0;
}
